In [ ]:
!pip install chromadb
!pip install dspy-ai
!pip install groq
!pip install -U sentence-transformers
!pip install langchain
!pip install -U langchain-community
!pip install gradio

Collecting chromadb
  Downloading chromadb-0.5.3-py3-none-any.whl (559 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.5/559.5 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.2.1)
Requirement already satisfied: requests>=2.28 in /usr/local/lib/python3.10/dist-packages (from chromadb) (2.31.0)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.10/dist-packages (from chromadb) (2.8.0)
Collecting chroma-hnswlib==0.7.3 (from chromadb)
  Downloading chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 44.7 MB/s eta 0:00:00
Collecting fastapi>=0.95.2 (from chromadb)
  Downloading fastapi-0.111.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 10.9 MB/s eta 0:00:00
Collecting uvicorn[standard]>=0.18.3 (from chromadb)
  Downloading uvicorn-0.30.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 8.0 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.0.0,>=1.22.5 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.25.2)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-3.5.0-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 5.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (4.12.2)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.18.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 77.2 MB/s eta 0:00:00
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.25.0-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 7.0 MB/s eta 0:00:00
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.25.0-py3-none-any.whl (18 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.46b0-py3-none-any.whl (11 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.25.0-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 15.0 MB/s eta 0:00:00
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.19.1)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 10.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (4.66.4)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from chromadb) (6.4.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.64.1)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.1.3-cp39-abi3-manylinux_2_28_x86_64.whl (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.7/283.7 kB 28.6 MB/s eta 0:00:00
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.12.3)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-30.1.0-py2.py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 53.3 MB/s eta 0:00:00
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.10/dist-packages (from chromadb) (8.4.2)
Requirement already satisfied: PyYAML>=6.0.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (6.0.1)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-4.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.6/67.6 kB 9.0 MB/s eta 0:00:00
Collecting orjson>=3.9.12 (from chromadb)
  Downloading orjson-3.10.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.1/141.1 kB 18.9 MB/s eta 0:00:00
Collecting httpx>=0.27.0 (from chromadb)
  Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 10.7 MB/s eta 0:00:00
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (24.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (1.1.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (2.0.1)
Collecting starlette<0.38.0,>=0.37.2 (from fastapi>=0.95.2->chromadb)
  Downloading starlette-0.37.2-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 9.9 MB/s eta 0:00:00
Collecting fastapi-cli>=0.0.2 (from fastapi>=0.95.2->chromadb)
  Downloading fastapi_cli-0.0.4-py3-none-any.whl (9.5 kB)
Requirement already satisfied: jinja2>=2.11.2 in /usr/local/lib/python3.10/dist-packages (from fastapi>=0.95.2->chromadb) (3.1.4)
Collecting python-multipart>=0.0.7 (from fastapi>=0.95.2->chromadb)
  Downloading python_multipart-0.0.9-py3-none-any.whl (22 kB)
Collecting ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1 (from fastapi>=0.95.2->chromadb)
  Downloading ujson-5.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 7.0 MB/s eta 0:00:00
Collecting email_validator>=2.0.0 (from fastapi>=0.95.2->chromadb)
  Downloading email_validator-2.2.0-py3-none-any.whl (33 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (2024.6.2)
Collecting httpcore==1.* (from httpx>=0.27.0->chromadb)
  Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 10.9 MB/s eta 0:00:00
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (1.3.1)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.27.0->chromadb)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.7)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (24.3.25)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.12.1)
Collecting deprecated>=1.2.6 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Collecting importlib-metadata<=7.1,>=6.0 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.63.2)
Collecting opentelemetry-exporter-otlp-proto-common==1.25.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.25.0-py3-none-any.whl (17 kB)
Collecting opentelemetry-proto==1.25.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.25.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 kB 5.4 MB/s eta 0:00:00
Collecting opentelemetry-instrumentation-asgi==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.46b0-py3-none-any.whl (14 kB)
Collecting opentelemetry-instrumentation==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.46b0-py3-none-any.whl (29 kB)
Collecting opentelemetry-semantic-conventions==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.46b0-py3-none-any.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.5/130.5 kB 16.4 MB/s eta 0:00:00
Collecting opentelemetry-util-http==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.46b0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: setuptools>=16.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.46b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (67.7.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.46b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (1.14.1)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.46b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Downloading monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (2.20.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.28->chromadb) (3.3.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from tokenizers>=0.13.2->chromadb) (0.23.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (13.7.1)
Collecting httptools>=0.5.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.4/341.4 kB 34.6 MB/s eta 0:00:00
Collecting python-dotenv>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.19.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 80.7 MB/s eta 0:00:00
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 70.7 MB/s eta 0:00:00
Collecting websockets>=10.4 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 18.0 MB/s eta 0:00:00
Collecting dnspython>=2.0.0 (from email_validator>=2.0.0->fastapi>=0.95.2->chromadb)
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 33.6 MB/s eta 0:00:00
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2023.6.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<=7.1,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.19.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.11.2->fastapi>=0.95.2->chromadb) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer>=0.9.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer>=0.9.0->chromadb) (2.16.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx>=0.27.0->chromadb) (1.2.1)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 11.7 MB/s eta 0:00:00
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.9.0->chromadb) (0.1.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.0)
Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml) ... done
  Created wheel for pypika: filename=PyPika-0.48.9-py2.py3-none-any.whl size=53724 sha256=da61b514bc3fc182d9bdb2f8ef66905f59486130d75b8477816a3853bc5aa4bb
  Stored in directory: /root/.cache/pip/wheels/e1/26/51/d0bffb3d2fd82256676d7ad3003faea3bd6dddc9577af665f4
Successfully built pypika
Installing collected packages: pypika, monotonic, mmh3, websockets, uvloop, ujson, python-multipart, python-dotenv, overrides, orjson, opentelemetry-util-http, opentelemetry-proto, importlib-metadata, humanfriendly, httptools, h11, dnspython, deprecated, chroma-hnswlib, bcrypt, backoff, asgiref, watchfiles, uvicorn, starlette, posthog, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, httpcore, email_validator, coloredlogs, opentelemetry-semantic-conventions, opentelemetry-instrumentation, onnxruntime, kubernetes, httpx, opentelemetry-sdk, opentelemetry-instrumentation-asgi, fastapi-cli, opentelemetry-instrumentation-fastapi, opentelemetry-exporter-otlp-proto-grpc, fastapi, chromadb
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 8.0.0
    Uninstalling importlib_metadata-8.0.0:
      Successfully uninstalled importlib_metadata-8.0.0
Successfully installed asgiref-3.8.1 backoff-2.2.1 bcrypt-4.1.3 chroma-hnswlib-0.7.3 chromadb-0.5.3 coloredlogs-15.0.1 deprecated-1.2.14 dnspython-2.6.1 email_validator-2.2.0 fastapi-0.111.0 fastapi-cli-0.0.4 h11-0.14.0 httpcore-1.0.5 httptools-0.6.1 httpx-0.27.0 humanfriendly-10.0 importlib-metadata-7.1.0 kubernetes-30.1.0 mmh3-4.1.0 monotonic-1.6 onnxruntime-1.18.1 opentelemetry-api-1.25.0 opentelemetry-exporter-otlp-proto-common-1.25.0 opentelemetry-exporter-otlp-proto-grpc-1.25.0 opentelemetry-instrumentation-0.46b0 opentelemetry-instrumentation-asgi-0.46b0 opentelemetry-instrumentation-fastapi-0.46b0 opentelemetry-proto-1.25.0 opentelemetry-sdk-1.25.0 opentelemetry-semantic-conventions-0.46b0 opentelemetry-util-http-0.46b0 orjson-3.10.6 overrides-7.7.0 posthog-3.5.0 pypika-0.48.9 python-dotenv-1.0.1 python-multipart-0.0.9 starlette-0.37.2 ujson-5.10.0 uvicorn-0.30.1 uvloop-0.19.0 watchfiles-0.22.0 websockets-12.0
Collecting dspy-ai
  Downloading dspy_ai-2.4.10-py3-none-any.whl (273 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.1/273.1 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: backoff~=2.2.1 in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (2.2.1)
Collecting joblib~=1.3.2 (from dspy-ai)
  Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 31.6 MB/s eta 0:00:00
Collecting openai<2.0.0,>=0.28.1 (from dspy-ai)
  Downloading openai-1.35.10-py3-none-any.whl (328 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.3/328.3 kB 36.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (2.0.3)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (2024.5.15)
Requirement already satisfied: ujson in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (5.10.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (4.66.4)
Collecting datasets<3.0.0,>=2.14.6 (from dspy-ai)
  Downloading datasets-2.20.0-py3-none-any.whl (547 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 44.6 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (2.31.0)
Collecting optuna (from dspy-ai)
  Downloading optuna-3.6.1-py3-none-any.whl (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 36.7 MB/s eta 0:00:00
Requirement already satisfied: pydantic~=2.0 in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (2.8.0)
Collecting structlog (from dspy-ai)
  Downloading structlog-24.2.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 8.7 MB/s eta 0:00:00
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from dspy-ai) (3.1.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets<3.0.0,>=2.14.6->dspy-ai) (3.15.4)

In [ ]:
import chromadb
import os
import pandas as pd
from sentence_transformers import SentenceTransformer
import dspy
from dspy.retrieve.chromadb_rm import ChromadbRM
from sklearn.model_selection import train_test_split
import langchain
from langchain.document_loaders import CSVLoader
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
from langchain.text_splitter import RecursiveCharacterTextSplitter, SentenceTransformersTokenTextSplitter
import regex as re
from groq import Groq

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [ ]:
os.environ['GROQ_API_KEY'] = ''

### Converting csv to document

In [ ]:
df=pd.read_csv('final.csv')
# df.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
df.head()

,question,answer
0,Is there a review of Grand Park Hotel in New Y...,The Grand Park Hotel exceeded all my expectati...
1,What is the location of Grand Park Hotel?,"New York City, USA"
2,What is the most memorable experience you had ...,The Grand Park Hotel exceeded all my expectati...
3,What is the review of Sunset Beach Resort in P...,I had an amazing experience at the Sunset Beac...
4,What is the location of Sunset Beach Resort?,"Phuket, Thailand"

In [ ]:
loader = CSVLoader("./final.csv", encoding="windows-1252")
documents = loader.load()

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  warn_deprecated(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
documents[0].page_content

": 0\nquestion: Is there a review of Grand Park Hotel in New York City?\nanswer: The Grand Park Hotel exceeded all my expectations. The staff was friendly and accommodating, and the rooms were luxurious and comfortable. The hotel's location in the heart of New York City made it convenient to explore the city's attractions. I would highly recommend this hotel to anyone visiting New York City."

### Creating Dspy custom dataset

In [ ]:
dataset = []

for question, answer in df.values:
    dataset.append(dspy.Example(question=question, answer=answer).with_inputs("question"))

print(dataset[:3])

[Example({'question': 'Is there a review of Grand Park Hotel in New York City?', 'answer': "The Grand Park Hotel exceeded all my expectations. The staff was friendly and accommodating, and the rooms were luxurious and comfortable. The hotel's location in the heart of New York City made it convenient to explore the city's attractions. I would highly recommend this hotel to anyone visiting New York City."}) (input_keys={'question'}), Example({'question': 'What is the location of Grand Park Hotel?', 'answer': 'New York City, USA'}) (input_keys={'question'}), Example({'question': 'What is the most memorable experience you had at the Grand Park Hotel?', 'answer': "The Grand Park Hotel exceeded all my expectations. The staff was friendly and accommodating, and the rooms were luxurious and comfortable. The hotel's location in the heart of New York City made it convenient to explore the city's attractions. I would highly recommend this hotel to anyone visiting New York City."}) (input_keys={'question'})]

### Splitting the data and creating chunks,embeddings and ingestion to chromadb

In [ ]:
# Perform the train-test split
train_df, test_df = train_test_split(dataset, test_size=0.2, random_state=42)

# Display the shapes of the resulting DataFrames
print(f"Train DataFrame shape: {len(train_df)}")
print(f"Test DataFrame shape: {(test_df)}")

Train DataFrame shape: 252
Test DataFrame shape: 63

In [ ]:
train_df[:2]

[Example({'question': "What are the hotel's amenities?", 'answer': "Golden Sands Hotel provided a fantastic experience in Miami. The beachfront location was perfect, and the views were stunning. The rooms were spacious, clean, and well-appointed. The staff was friendly, attentive, and provided exceptional service. The hotel's amenities, including the pool and beach access, were excellent. I would highly recommend Golden Sands Hotel for a memorable stay in Miami."}) (input_keys={'question'}),
 Example({'question': 'What is the review of Mountain View Resort in Lake Tahoe, USA?', 'answer': "Mountain View Resort provided a spectacular mountain retreat in Lake Tahoe. The resort's location amidst the towering Sierra Nevada mountains and crystal-clear lake was breathtaking. The rooms were spacious, elegantly furnished, and offered stunning views of the surrounding nature. The staff was warm, attentive, and provided excellent recommendations for outdoor activities such as hiking and skiing. After a day of adventure, unwinding by the resort's fireplace was pure bliss. I would highly recommend Mountain View Resort for a memorable stay in Lake Tahoe."}) (input_keys={'question'})]

In [ ]:
texts=[text.page_content for text in documents]
texts[0]

": 0\nquestion: Is there a review of Grand Park Hotel in New York City?\nanswer: The Grand Park Hotel exceeded all my expectations. The staff was friendly and accommodating, and the rooms were luxurious and comfortable. The hotel's location in the heart of New York City made it convenient to explore the city's attractions. I would highly recommend this hotel to anyone visiting New York City."

In [ ]:
#step 1
character_splitter = RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", ". ", " ", ""],
    chunk_size=1000,
    chunk_overlap=0
)
character_split_texts = character_splitter.split_text('\n\n'.join(texts))

In [ ]:
print((character_split_texts[10]))
print(f"\nTotal chunks: {len(character_split_texts)}")

: 20
question: What was the most memorable experience you had at Seaside Paradise Resort?
answer: My vacation at Seaside Paradise Resort was nothing short of amazing. The resort's prime beachfront location offered crystal-clear turquoise waters and pristine white sand. The rooms were spacious, clean, and tastefully decorated. The resort's pool area was a tropical oasis, complete with palm trees and refreshing cocktails. The staff was attentive and friendly, ensuring that every aspect of my stay was perfect. I would return to Seaside Paradise Resort in a heartbeat.

Total chunks: 184

In [ ]:
#step 2
#to ensure data is within embeddings context window length
token_splitter = SentenceTransformersTokenTextSplitter(chunk_overlap=0, tokens_per_chunk=256)

token_split_texts = []
for text in character_split_texts:
    token_split_texts += token_splitter.split_text(text)

print((token_split_texts[10]))
print(f"\nTotal chunks: {len(token_split_texts)}")

: 20 question : what was the most memorable experience you had at seaside paradise resort? answer : my vacation at seaside paradise resort was nothing short of amazing. the resort's prime beachfront location offered crystal - clear turquoise waters and pristine white sand. the rooms were spacious, clean, and tastefully decorated. the resort's pool area was a tropical oasis, complete with palm trees and refreshing cocktails. the staff was attentive and friendly, ensuring that every aspect of my stay was perfect. i would return to seaside paradise resort in a heartbeat.

Total chunks: 184

In [ ]:
embedding_function = SentenceTransformerEmbeddingFunction()

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
chroma_client = chromadb.PersistentClient(path="/content/drive/MyDrive/chroma")
chroma_collection = chroma_client.create_collection("hoteldata", embedding_function=embedding_function)

ids = [str(i) for i in range(len(token_split_texts))]

chroma_collection.add(ids=ids, documents=token_split_texts)
chroma_collection.count()

184

In [ ]:
retriever_model = ChromadbRM(
    'hoteldata',
    '/content/drive/MyDrive/chroma',
    embedding_function=embedding_function,
    k=3
)

### configuring dspy

In [ ]:
llama3 = dspy.GROQ(model='llama3-8b-8192', api_key=os.environ['GROQ_API_KEY'])

In [ ]:
dspy.settings.configure(rm=retriever_model, lm=llama3)

In [ ]:
class GenerateAnswer(dspy.Signature):
    """Answer questions with short relevant answers."""

    context = dspy.InputField(desc="may contain relevant information")
    question = dspy.InputField()
    answer = dspy.OutputField(desc="give a recommendation between 10-15 words")
    # reason = dspy.OutputField(desc="give relevant,logical reasoning for the recommendation")

In [ ]:
class RAG(dspy.Module):
    def __init__(self, num_passages=3):
        super().__init__()

        self.retrieve = dspy.Retrieve(k=num_passages)
        self.generate_answer = dspy.ChainOfThought(GenerateAnswer)

    def forward(self, question):
        context = self.retrieve(question).passages
        prediction = self.generate_answer(context=context, question=question)
        return dspy.Prediction(context=context, answer=prediction.answer)

In [ ]:
class Assess(dspy.Signature):
    """Assess the quality of an answer along the specified dimension."""
    assessed_text = dspy.InputField()
    assessment_question = dspy.InputField()
    assessment_answer = dspy.OutputField(desc="Only output an integer score between 0-10 and nothing else")

def extract_score(text):
    matches = re.findall(r'\d+', text)
    if matches:
        return int(matches[-1])
    else:
        return -1  # Default value if no integer is found

def metric(example, pred, trace=None):
    question, answer, context, prediction = example.question, example.answer, pred.context, pred.answer
    #converting list to str
    context = " ".join(context)
    # print(context[:200])

    # Content relevance assessment question
    content_question =f"Does the assessed text answer the question '{question}' deriving from or similar to '{answer}'?"
    # # Correctness assessment question while passing context length of 200 characters to ensure assessment answer for the query
    correct_question = f"Is the assessed text relevant to {context[:200]}?"
    # exact_question = f"Is the assessed similar to'{answer}'?"

    with dspy.context(lm=llama3):
        # Ensure questions are passed as strings
        content_assessment = dspy.Predict(Assess)(assessed_text=prediction, assessment_question=content_question)
        correct_assessment = dspy.Predict(Assess)(assessed_text=prediction, assessment_question=correct_question)



    content_score=extract_score(content_assessment.assessment_answer)
    correct_score=extract_score(correct_assessment.assessment_answer)
    # print(content_score)
    # print(correct_score)
    score=(content_score+correct_score)
    if trace is not None:
        return score >= 0.5
    return score / 20.0

In [ ]:
#optimize
from dspy.teleprompt import BootstrapFewShotWithRandomSearch

config = dict(max_bootstrapped_demos=4, max_labeled_demos=4, num_candidate_programs=2, num_threads=4)
# Set up teleprompter which will compile our RAG program
teleprompter = BootstrapFewShotWithRandomSearch(metric=metric,**config)

# Compile!
compiled_rag = teleprompter.compile(RAG(), trainset=train_df)

Average Metric: 3.9500000000000006 / 9  (43.9):   4%|▎         | 9/252 [00:06<03:51,  1.05it/s]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.976s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.977s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 4.15 / 10  (41.5):   4%|▍         | 10/252 [00:22<22:14,  5.52s/it]

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.712s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.599s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 4.65 / 11  (42.3):   4%|▍         | 11/252 [00:26<20:56,  5.22s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.295s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 5.25 / 12  (43.8):   5%|▍         | 12/252 [00:33<23:13,  5.81s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.393s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.717s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.868s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 5.35 / 13  (41.2):   5%|▌         | 13/252 [00:38<21:48,  5.48s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.697s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 9.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.661s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 9.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.25 / 14  (44.6):   6%|▌         | 14/252 [00:45<22:51,  5.76s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.501s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 4.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.642s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 4.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 21.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 21.1 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 7.35 / 16  (45.9):   6%|▋         | 16/252 [01:00<24:48,  6.31s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.143s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.483s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.954s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 7.85 / 17  (46.2):   7%|▋         | 17/252 [01:09<27:55,  7.13s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.64s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 9.55 / 19  (50.3):   8%|▊         | 19/252 [01:21<24:27,  6.30s/it]INFO:backoff:Backing off request(...) for 15.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.633s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.59s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 15.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 12.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.288s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 12.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.874s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 9.65 / 20  (48.2):   8%|▊         | 20/252 [01:28<25:23,  6.57s/it]INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.929s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 10.15 / 21  (48.3):   8%|▊         | 21/252 [01:38<29:21,  7.62s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.997s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 10.5 / 22  (47.7):   9%|▊         | 22/252 [01:40<23:01,  6.01s/it]INFO:backoff:Backing off request(...) for 27.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.492s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 27.6 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.853s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.916s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 11.5 / 23  (50.0):   9%|▉         | 23/252 [01:50<26:45,  7.01s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.759s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 11.7 / 24  (48.8):  10%|▉         | 24/252 [01:56<26:14,  6.91s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 12.5 / 25  (50.0):  10%|▉         | 25/252 [01:59<20:51,  5.51s/it]

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 12.55 / 26  (48.3):  10%|█         | 26/252 [02:12<29:58,  7.96s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.843s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 40.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}
Backing off 40.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.456999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.956s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 13.450000000000001 / 27  (49.8):  11%|█         | 27/252 [02:21<30:58,  8.26s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.652s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 13.55 / 28  (48.4):  11%|█         | 28/252 [02:29<30:09,  8.08s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.714s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.958s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 14.0 / 29  (48.3):  12%|█▏        | 29/252 [02:36<28:27,  7.66s/it]

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.1 / 30  (47.0):  12%|█▏        | 30/252 [02:42<27:20,  7.39s/it]INFO:backoff:Backing off request(...) for 6.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.627s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.2 / 31  (45.8):  12%|█▏        | 31/252 [02:49<26:30,  7.20s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.856s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.569s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.771s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.649999999999999 / 33  (44.4):  13%|█▎        | 33/252 [03:03<24:32,  6.73s/it]INFO:backoff:Backing off request(...) for 29.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 29.7 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 12.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.942s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 12.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.2 / 34  (44.7):  13%|█▎        | 34/252 [03:12<26:57,  7.42s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.714s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.05 / 35  (45.9):  14%|█▍        | 35/252 [03:19<26:11,  7.24s/it]INFO:backoff:Backing off request(...) for 16.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 16.7 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.939s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 16.400000000000002 / 36  (45.6):  14%|█▍        | 36/252 [03:28<28:14,  7.84s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.979s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 17.200000000000003 / 37  (46.5):  15%|█▍        | 37/252 [03:36<27:34,  7.70s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.672s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 17.6 / 38  (46.3):  15%|█▌        | 38/252 [03:40<23:45,  6.66s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 57.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}
Backing off 57.6 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 18.05 / 39  (46.3):  15%|█▌        | 39/252 [03:52<28:43,  8.09s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.667s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.321s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 18.55 / 40  (46.4):  16%|█▌        | 40/252 [03:58<27:07,  7.68s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.669s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.713s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.05 / 42  (47.7):  17%|█▋        | 42/252 [04:12<23:41,  6.77s/it]INFO:backoff:Backing off request(...) for 7.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.412s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.400000000000002 / 43  (47.4):  17%|█▋        | 43/252 [04:23<28:22,  8.14s/it]INFO:backoff:Backing off request(...) for 11.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.601999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.8 / 44  (47.3):  17%|█▋        | 44/252 [04:25<22:22,  6.45s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.3 / 45  (47.3):  18%|█▊        | 45/252 [04:32<22:34,  6.55s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.733s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.952s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 21.400000000000002 / 46  (46.5):  18%|█▊        | 46/252 [04:39<22:54,  6.67s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.873s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.0 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.639s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.8 / 47  (46.4):  19%|█▊        | 47/252 [04:48<25:22,  7.42s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.945s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.646s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.643s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 22.3 / 48  (46.5):  19%|█▉        | 48/252 [04:55<24:49,  7.30s/it]

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.546s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.238s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.5 / 49  (45.9):  19%|█▉        | 49/252 [05:02<23:42,  7.01s/it]INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.464s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.964s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.471s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.392s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.5 / 50  (45.0):  20%|█▉        | 50/252 [05:15<30:00,  8.91s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.781s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.1 / 51  (45.3):  20%|██        | 51/252 [05:17<23:07,  6.90s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 23.5 / 52  (45.2):  21%|██        | 52/252 [05:20<18:39,  5.60s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.403s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.9 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.682s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.931s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.0 / 53  (45.3):  21%|██        | 53/252 [05:31<23:41,  7.14s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.676s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 51.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.472s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}
Backing off 51.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.931s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 24.1 / 54  (44.6):  21%|██▏       | 54/252 [05:35<20:50,  6.32s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.628s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.563s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.97s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.0 / 56  (44.6):  22%|██▏       | 56/252 [05:53<22:50,  6.99s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.471s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.349s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.1 / 57  (44.0):  23%|██▎       | 57/252 [05:57<20:22,  6.27s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.879s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.674s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}
Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.908s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.985s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 26.0 / 58  (44.8):  23%|██▎       | 58/252 [06:08<24:30,  7.58s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.732s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 26.1 / 59  (44.2):  23%|██▎       | 59/252 [06:16<24:58,  7.77s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.945s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 26.55 / 60  (44.2):  24%|██▍       | 60/252 [06:23<23:50,  7.45s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.745s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 27.400000000000002 / 61  (44.9):  24%|██▍       | 61/252 [06:29<22:47,  7.16s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 27.900000000000002 / 62  (45.0):  25%|██▍       | 62/252 [06:32<17:57,  5.67s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.366s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.833s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.755s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.789s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.68s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.853s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.939s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 28.750000000000004 / 64  (44.9):  25%|██▌       | 64/252 [06:50<21:19,  6.80s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 28.950000000000003 / 65  (44.5):  26%|██▌       | 65/252 [06:52<16:54,  5.42s/it]

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.728s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.787s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 7.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.682s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 7.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.742s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.922s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.450000000000003 / 66  (44.6):  26%|██▌       | 66/252 [07:03<22:18,  7.20s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.537s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.500000000000004 / 67  (44.0):  27%|██▋       | 67/252 [07:15<25:55,  8.41s/it]INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.711s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.000000000000004 / 68  (44.1):  27%|██▋       | 68/252 [07:17<20:04,  6.54s/it]INFO:backoff:Backing off request(...) for 9.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.345s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 9.8 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.472999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 30.900000000000002 / 69  (44.8):  27%|██▋       | 69/252 [07:26<22:12,  7.28s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 31.1 / 70  (44.4):  28%|██▊       | 70/252 [07:29<17:53,  5.90s/it]INFO:backoff:Backing off request(...) for 47.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.738999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 47.0 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.709s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.493s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 31.5 / 71  (44.4):  28%|██▊       | 71/252 [07:42<24:31,  8.13s/it]INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 32.35 / 72  (44.9):  29%|██▊       | 72/252 [07:44<18:58,  6.33s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.931s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 32.550000000000004 / 73  (44.6):  29%|██▉       | 73/252 [07:53<21:28,  7.20s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.974s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.789s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.805s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.888s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 32.650000000000006 / 74  (44.1):  29%|██▉       | 74/252 [08:05<25:11,  8.49s/it]

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 33.050000000000004 / 75  (44.1):  30%|██▉       | 75/252 [08:07<19:41,  6.68s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.555s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.996s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 33.85 / 76  (44.5):  30%|███       | 76/252 [08:21<25:37,  8.74s/it]INFO:backoff:Backing off request(...) for 64.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.476s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 64.8 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.2 / 77  (44.4):  31%|███       | 77/252 [08:23<19:35,  6.72s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.832s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.643s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.550000000000004 / 78  (44.3):  31%|███       | 78/252 [08:27<17:41,  6.10s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.334s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.895s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.650000000000006 / 79  (43.9):  31%|███▏      | 79/252 [08:34<18:04,  6.27s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.628s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 35.00000000000001 / 80  (43.8):  32%|███▏      | 80/252 [08:41<18:37,  6.50s/it]

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.873s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 35.35000000000001 / 81  (43.6):  32%|███▏      | 81/252 [08:45<16:41,  5.86s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.57s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 35.400000000000006 / 82  (43.2):  33%|███▎      | 82/252 [08:59<23:08,  8.17s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.411s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 35.900000000000006 / 83  (43.3):  33%|███▎      | 83/252 [09:01<18:02,  6.40s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.492s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.661s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 36.150000000000006 / 85  (42.5):  34%|███▎      | 85/252 [09:15<17:08,  6.16s/it]INFO:backoff:Backing off request(...) for 8.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.97s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.747s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 36.650000000000006 / 86  (42.6):  34%|███▍      | 86/252 [09:24<19:37,  7.10s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 184.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.440999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 184.0 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.45 / 87  (43.0):  35%|███▍      | 87/252 [09:31<19:19,  7.03s/it]INFO:backoff:Backing off request(...) for 3.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.361s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.75 / 89  (43.5):  35%|███▌      | 89/252 [09:42<16:27,  6.06s/it]INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.742s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.35s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.947s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.794s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 39.300000000000004 / 91  (43.2):  36%|███▌      | 91/252 [09:59<18:10,  6.78s/it]INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.806s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 39.7 / 92  (43.2):  37%|███▋      | 92/252 [10:10<21:28,  8.05s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.611s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.2 / 93  (43.2):  37%|███▋      | 93/252 [10:12<16:40,  6.29s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.78s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.323s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.400000000000006 / 94  (43.0):  37%|███▋      | 94/252 [10:24<20:38,  7.84s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.567s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.60000000000001 / 95  (42.7):  38%|███▊      | 95/252 [10:26<16:08,  6.17s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.816s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.591s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.894s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 40.60000000000001 / 96  (42.3):  38%|███▊      | 96/252 [10:37<19:59,  7.69s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.842s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.400000000000006 / 97  (42.7):  38%|███▊      | 97/252 [10:42<17:47,  6.89s/it]INFO:backoff:Backing off request(...) for 5.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.345s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.7 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.900000000000006 / 98  (42.8):  39%|███▉      | 98/252 [10:47<15:39,  6.10s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 60.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.533s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 60.3 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.858s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 43.00000000000001 / 100  (43.0):  40%|███▉      | 100/252 [11:01<15:43,  6.21s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.998s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 43.900000000000006 / 101  (43.5):  40%|████      | 101/252 [11:15<21:16,  8.45s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.688s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.00000000000001 / 102  (43.1):  40%|████      | 102/252 [11:22<20:06,  8.04s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.883s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.20000000000001 / 104  (43.5):  41%|████▏     | 104/252 [11:31<15:09,  6.14s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.755s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.45000000000001 / 106  (42.9):  42%|████▏     | 106/252 [11:50<18:15,  7.51s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.99s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.933s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 45.85000000000001 / 107  (42.9):  42%|████▏     | 107/252 [11:57<17:41,  7.32s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.402s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.467s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.35000000000001 / 108  (42.9):  43%|████▎     | 108/252 [12:04<17:28,  7.28s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.729s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.554s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.45000000000001 / 109  (42.6):  43%|████▎     | 109/252 [12:11<16:59,  7.13s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.95000000000001 / 110  (42.7):  44%|████▎     | 110/252 [12:13<13:37,  5.76s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.71s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.954s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.933s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 47.75000000000001 / 111  (43.0):  44%|████▍     | 111/252 [12:29<20:20,  8.65s/it]

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 47.95000000000001 / 112  (42.8):  44%|████▍     | 112/252 [12:31<15:46,  6.76s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.986s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 48.15000000000001 / 113  (42.6):  45%|████▍     | 113/252 [12:33<12:25,  5.36s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.628s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.786s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 7.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.649s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 7.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.796s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.60000000000001 / 115  (42.3):  46%|████▌     | 115/252 [12:47<13:07,  5.75s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.848s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.688s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.89s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.05000000000001 / 116  (42.3):  46%|████▌     | 116/252 [12:54<13:37,  6.01s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.27s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.406s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.39s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.647s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.45000000000001 / 117  (42.3):  46%|████▋     | 117/252 [13:03<15:28,  6.88s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.659s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.472s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.31s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.85000000000001 / 118  (42.2):  47%|████▋     | 118/252 [13:10<15:47,  7.07s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.293s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.25000000000001 / 119  (42.2):  47%|████▋     | 119/252 [13:16<14:49,  6.69s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.501s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.300000000000004 / 120  (41.9):  48%|████▊     | 120/252 [13:23<14:40,  6.67s/it]INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.779s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.607s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.400000000000006 / 121  (41.7):  48%|████▊     | 121/252 [13:29<14:34,  6.68s/it]INFO:backoff:Backing off request(...) for 4.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.497s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 8.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.422s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 8.7 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.95 / 122  (41.8):  48%|████▊     | 122/252 [13:36<14:29,  6.69s/it]INFO:backoff:Backing off request(...) for 14.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.52s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 14.3 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 51.0 / 123  (41.5):  49%|████▉     | 123/252 [13:43<14:24,  6.70s/it]INFO:backoff:Backing off request(...) for 16.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 16.7 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.935s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 52.0 / 124  (41.9):  49%|████▉     | 124/252 [13:47<12:56,  6.07s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.996s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 52.5 / 125  (42.0):  50%|████▉     | 125/252 [13:59<16:24,  7.76s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 43.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.417s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 43.0 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 15.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.758s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 15.0 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 52.85 / 126  (41.9):  50%|█████     | 126/252 [14:08<17:11,  8.19s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.644s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.682s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.2 / 127  (41.9):  50%|█████     | 127/252 [14:17<17:12,  8.26s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.5 / 128  (41.8):  51%|█████     | 128/252 [14:21<14:22,  6.95s/it]INFO:backoff:Backing off request(...) for 122.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.607s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 122.2 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 54.9 / 131  (41.9):  52%|█████▏    | 131/252 [14:41<13:50,  6.86s/it]INFO:backoff:Backing off request(...) for 93.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.476s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 93.9 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.1 / 132  (41.7):  52%|█████▏    | 132/252 [14:50<15:10,  7.58s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.569s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.9 / 133  (42.0):  53%|█████▎    | 133/252 [14:55<13:13,  6.67s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.917s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.0 / 134  (41.8):  53%|█████▎    | 134/252 [15:04<14:41,  7.47s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.812s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.0 / 135  (42.2):  54%|█████▎    | 135/252 [15:07<11:32,  5.92s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 58.699999999999996 / 138  (42.5):  55%|█████▍    | 138/252 [15:29<13:04,  6.88s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.099999999999994 / 139  (42.5):  55%|█████▌    | 139/252 [15:39<14:18,  7.59s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.902s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.65 / 141  (42.3):  56%|█████▌    | 141/252 [15:53<12:37,  6.83s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.992s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 59.699999999999996 / 142  (42.0):  56%|█████▋    | 142/252 [16:02<13:52,  7.57s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.74999999999999 / 143  (41.8):  57%|█████▋    | 143/252 [16:09<13:31,  7.45s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.99999999999999 / 145  (41.4):  58%|█████▊    | 145/252 [16:21<11:14,  6.31s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.984s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 65.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.794s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 65.1 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.648s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.54999999999999 / 146  (41.5):  58%|█████▊    | 146/252 [16:30<12:54,  7.31s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.686s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.577s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 61.54999999999999 / 147  (41.9):  58%|█████▊    | 147/252 [16:35<11:19,  6.47s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.99s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.64999999999999 / 148  (41.7):  59%|█████▊    | 148/252 [16:44<12:27,  7.19s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.436s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.99s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 62.14999999999999 / 149  (41.7):  59%|█████▉    | 149/252 [16:48<10:59,  6.41s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.955s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 62.74999999999999 / 151  (41.6):  60%|█████▉    | 151/252 [17:02<10:23,  6.18s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.517s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.962s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.962s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 63.199999999999996 / 152  (41.6):  60%|██████    | 152/252 [17:13<12:45,  7.66s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.852s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.6s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.781s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.05 / 153  (41.9):  61%|██████    | 153/252 [17:23<13:37,  8.25s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.496s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.797s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.14999999999999 / 154  (41.7):  61%|██████    | 154/252 [17:29<12:39,  7.75s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 64.74999999999999 / 155  (41.8):  62%|██████▏   | 155/252 [17:31<09:48,  6.07s/it]

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 319.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.443s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 319.0 seconds after 10 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.369s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.902s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.84999999999998 / 156  (41.6):  62%|██████▏   | 156/252 [17:43<12:11,  7.62s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.89s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.67s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 64.94999999999997 / 157  (41.4):  62%|██████▏   | 157/252 [17:49<11:43,  7.41s/it]INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.738s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.89999999999998 / 158  (41.1):  63%|██████▎   | 158/252 [17:57<11:26,  7.31s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.782s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.94999999999997 / 159  (40.8):  63%|██████▎   | 159/252 [18:08<13:29,  8.71s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.865s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 64.99999999999997 / 160  (40.6):  63%|██████▎   | 160/252 [18:15<12:25,  8.10s/it]

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.49999999999997 / 161  (40.7):  64%|██████▍   | 161/252 [18:17<09:37,  6.35s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.577s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.736s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 66.04999999999997 / 162  (40.8):  64%|██████▍   | 162/252 [18:29<11:49,  7.88s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.936s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 66.54999999999997 / 163  (40.8):  65%|██████▍   | 163/252 [18:34<10:14,  6.91s/it]

Backing off 7.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.721s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.74999999999997 / 164  (40.7):  65%|██████▌   | 164/252 [18:45<12:02,  8.21s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.59999999999997 / 165  (41.0):  65%|██████▌   | 165/252 [18:47<09:27,  6.52s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.684s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.675s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.593999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.64999999999996 / 166  (40.8):  66%|██████▌   | 166/252 [18:58<11:13,  7.83s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.834s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.99999999999996 / 167  (40.7):  66%|██████▋   | 167/252 [19:01<08:55,  6.30s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.707s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 68.79999999999995 / 168  (41.0):  67%|██████▋   | 168/252 [19:07<08:53,  6.35s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.555s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 68.89999999999995 / 169  (40.8):  67%|██████▋   | 169/252 [19:15<09:07,  6.60s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.644s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.24999999999994 / 171  (41.1):  68%|██████▊   | 171/252 [19:30<09:03,  6.71s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.357s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 70.74999999999994 / 172  (41.1):  68%|██████▊   | 172/252 [19:41<10:41,  8.02s/it]

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.84999999999994 / 173  (41.0):  69%|██████▊   | 173/252 [19:44<08:19,  6.32s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.789s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.856s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.34999999999994 / 174  (41.0):  69%|██████▉   | 174/252 [19:55<10:07,  7.79s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.452s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.54999999999994 / 175  (40.9):  69%|██████▉   | 175/252 [19:57<07:53,  6.15s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.749s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.696s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.805s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.574s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 72.44999999999995 / 176  (41.2):  70%|██████▉   | 176/252 [20:09<09:56,  7.85s/it]

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.985s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.34999999999994 / 178  (41.2):  71%|███████   | 178/252 [20:22<08:26,  6.84s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.291s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 74.14999999999993 / 179  (41.4):  71%|███████   | 179/252 [20:27<07:39,  6.30s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 74.64999999999993 / 180  (41.5):  71%|███████▏  | 180/252 [20:38<09:15,  7.72s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.354s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.861s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.896s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.637s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.14999999999993 / 182  (41.8):  72%|███████▏  | 182/252 [20:50<07:26,  6.38s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.87s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.896s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.81s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 76.64999999999993 / 183  (41.9):  73%|███████▎  | 183/252 [20:59<08:19,  7.24s/it]

Backing off 6.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.689s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 77.44999999999993 / 184  (42.1):  73%|███████▎  | 184/252 [21:09<09:00,  7.95s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.908s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 77.79999999999993 / 185  (42.1):  73%|███████▎  | 185/252 [21:11<07:04,  6.34s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.877s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.568s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 78.64999999999993 / 187  (42.1):  74%|███████▍  | 187/252 [21:20<05:40,  5.24s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.554s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.668s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 78.69999999999993 / 188  (41.9):  75%|███████▍  | 188/252 [21:34<08:16,  7.76s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.962s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.69999999999993 / 189  (42.2):  75%|███████▌  | 189/252 [21:41<07:49,  7.46s/it]INFO:backoff:Backing off request(...) for 7.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.696s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 80.59999999999994 / 191  (42.2):  76%|███████▌  | 191/252 [21:52<06:32,  6.44s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.855s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.667s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.991s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 80.79999999999994 / 192  (42.1):  76%|███████▌  | 192/252 [22:01<07:12,  7.21s/it]INFO:backoff:Backing off request(...) for 23.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.341s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 23.9 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.956s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 81.39999999999993 / 193  (42.2):  77%|███████▋  | 193/252 [22:06<06:19,  6.44s/it]

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.04999999999994 / 196  (41.9):  78%|███████▊  | 196/252 [22:28<06:35,  7.07s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 60.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.584s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 60.2 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.692s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.04999999999993 / 199  (41.7):  79%|███████▉  | 199/252 [22:49<06:02,  6.85s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.936s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.973s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.14999999999992 / 200  (41.6):  79%|███████▉  | 200/252 [22:55<05:52,  6.79s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.984s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.533s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.24999999999991 / 201  (41.4):  80%|███████▉  | 201/252 [23:07<06:55,  8.15s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.343999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.661s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.34999999999991 / 202  (41.3):  80%|████████  | 202/252 [23:13<06:24,  7.69s/it]INFO:backoff:Backing off request(...) for 7.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.56s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.81s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.59999999999991 / 203  (41.2):  81%|████████  | 203/252 [23:23<06:44,  8.25s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.963s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 83.6999999999999 / 204  (41.0):  81%|████████  | 204/252 [23:25<05:08,  6.43s/it]

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.978s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 84.4999999999999 / 205  (41.2):  81%|████████▏ | 205/252 [23:27<04:04,  5.20s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.345s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 18.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.455s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 18.2 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.989s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.71s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 84.9999999999999 / 206  (41.3):  82%|████████▏ | 206/252 [23:41<05:53,  7.69s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.787s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.455s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.3999999999999 / 207  (41.3):  82%|████████▏ | 207/252 [23:48<05:31,  7.37s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.655s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.29999999999991 / 208  (41.5):  82%|████████▏ | 207/252 [23:54<05:31,  7.37s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 86.29999999999991 / 208  (41.5):  83%|████████▎ | 208/252 [23:54<05:13,  7.14s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.488999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 87.09999999999991 / 209  (41.7):  83%|████████▎ | 209/252 [23:57<04:05,  5.70s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.992s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 87.29999999999991 / 210  (41.6):  83%|████████▎ | 210/252 [23:59<03:14,  4.64s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.423s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.626s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.323s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.53s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 87.49999999999991 / 211  (41.5):  83%|████████▎ | 210/252 [24:12<03:14,  4.64s/it]INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 87.49999999999991 / 211  (41.5):  84%|████████▎ | 211/252 [24:12<04:57,  7.26s/it]

Backing off 3.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.634s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.573s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.843s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.617s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 87.59999999999991 / 212  (41.3):  84%|████████▍ | 212/252 [24:23<05:38,  8.46s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.755s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.04999999999991 / 213  (41.3):  85%|████████▍ | 213/252 [24:26<04:17,  6.62s/it]INFO:backoff:Backing off request(...) for 6.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.431s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.44999999999992 / 214  (41.3):  85%|████████▍ | 214/252 [24:30<03:44,  5.90s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.763s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 11.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.392s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.264s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.24999999999991 / 215  (41.5):  85%|████████▌ | 215/252 [24:41<04:38,  7.52s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.683s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.562s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.901s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 89.59999999999991 / 216  (41.5):  86%|████████▌ | 216/252 [24:50<04:47,  7.97s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 14.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.965s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 90.4499999999999 / 217  (41.7):  86%|████████▌ | 217/252 [24:52<03:39,  6.26s/it]

Backing off 14.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.762s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.958s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.9999999999999 / 219  (42.0):  87%|████████▋ | 219/252 [25:06<03:20,  6.09s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.802s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.883s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 29.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 29.1 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.646s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 92.5499999999999 / 221  (41.9):  88%|████████▊ | 221/252 [25:18<02:54,  5.61s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.686s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.933s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 93.89999999999989 / 223  (42.1):  88%|████████▊ | 223/252 [25:33<02:59,  6.20s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.808s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.853s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.977s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 94.2999999999999 / 224  (42.1):  89%|████████▉ | 224/252 [25:45<03:38,  7.82s/it]INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.443s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 95.1999999999999 / 225  (42.3):  89%|████████▉ | 225/252 [25:47<02:45,  6.12s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.773s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.943s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.746s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.658s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.974s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 95.9999999999999 / 226  (42.5):  90%|████████▉ | 226/252 [25:58<03:17,  7.60s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.868s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.984s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 96.0999999999999 / 227  (42.3):  90%|█████████ | 227/252 [26:02<02:46,  6.65s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 11.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.389s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 96.19999999999989 / 228  (42.2):  90%|█████████ | 228/252 [26:05<02:09,  5.41s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.398s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.989s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 96.29999999999988 / 229  (42.1):  91%|█████████ | 229/252 [26:14<02:27,  6.41s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.468s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.641s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 18.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.583s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 18.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.98s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 96.79999999999988 / 230  (42.1):  91%|█████████▏| 230/252 [26:25<02:53,  7.89s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.804s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 96.99999999999989 / 231  (42.0):  92%|█████████▏| 231/252 [26:32<02:40,  7.64s/it]INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.407s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.19999999999989 / 232  (41.9):  92%|█████████▏| 232/252 [26:36<02:11,  6.59s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 47.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.529s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 47.3 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.64999999999989 / 233  (41.9):  92%|█████████▏| 233/252 [26:48<02:34,  8.13s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.0999999999999 / 235  (41.7):  93%|█████████▎| 235/252 [26:55<01:39,  5.84s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.747s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.979s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.852s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.44999999999989 / 236  (41.7):  94%|█████████▎| 236/252 [27:09<02:11,  8.21s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.575s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.8499999999999 / 237  (41.7):  94%|█████████▍| 237/252 [27:11<01:37,  6.49s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.504s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.918s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.601999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 99.64999999999989 / 238  (41.9):  94%|█████████▍| 238/252 [27:18<01:31,  6.55s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.542s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.0999999999999 / 239  (41.9):  95%|█████████▍| 239/252 [27:24<01:25,  6.56s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.654s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.787s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.434s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.866s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 100.5499999999999 / 240  (41.9):  95%|█████████▌| 240/252 [27:35<01:34,  7.89s/it]

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.389s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.362s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.89999999999989 / 241  (41.9):  96%|█████████▌| 241/252 [27:42<01:22,  7.52s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.679s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.721s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.04999999999988 / 243  (42.0):  96%|█████████▋| 243/252 [27:56<01:00,  6.72s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.444s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.947s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.433s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.14999999999988 / 244  (41.9):  97%|█████████▋| 244/252 [28:05<00:59,  7.48s/it]INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.662s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 102.44999999999987 / 245  (41.8):  97%|█████████▋| 245/252 [28:11<00:50,  7.25s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 103.34999999999988 / 246  (42.0):  98%|█████████▊| 246/252 [28:14<00:34,  5.79s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.862s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.784s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.536s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 103.69999999999987 / 247  (42.0):  98%|█████████▊| 247/252 [28:23<00:33,  6.67s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.589s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.711s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 104.39999999999988 / 248  (42.1):  98%|█████████▊| 248/252 [28:30<00:26,  6.75s/it]

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.795s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 104.69999999999987 / 249  (42.0):  99%|█████████▉| 249/252 [28:36<00:20,  6.68s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.345s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 105.79999999999987 / 251  (42.2): 100%|█████████▉| 251/252 [28:43<00:04,  4.98s/it]INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.425s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 105.84999999999987 / 252  (42.0): 100%|██████████| 252/252 [28:50<00:00,  6.87s/it]
  0%|          | 0/252 [00:00<?, ?it/s]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.968s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.533s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.784s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.347s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.795s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 0.35 / 1  (35.0):   0%|          | 1/252 [00:15<1:05:53, 15.75s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.626s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.826s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.472999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.931s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 1.25 / 2  (62.5):   1%|          | 2/252 [00:24<48:46, 11.70s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.855s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.626s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}
Backing off 1.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 2.1 / 3  (70.0):   1%|          | 3/252 [00:35<47:35, 11.47s/it]INFO:backoff:Backing off request(...) for 5.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.472999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.438s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 2.6 / 4  (65.0):   2%|▏         | 4/252 [00:38<32:20,  7.83s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.436s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.951s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 9.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.480999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 9.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.736s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 3.2500000000000004 / 6  (54.2):   2%|▏         | 6/252 [00:53<29:52,  7.28s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.516s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.946s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 3.6500000000000004 / 7  (52.1):   3%|▎         | 7/252 [00:58<25:55,  6.35s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.407s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.724s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 4.15 / 8  (51.9):   3%|▎         | 8/252 [01:09<32:02,  7.88s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.651s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 57.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.337s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 57.8 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.608s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 4.3500000000000005 / 9  (48.3):   4%|▎         | 9/252 [01:18<33:24,  8.25s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 4.95 / 10  (49.5):   4%|▍         | 10/252 [01:20<26:03,  6.46s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.66s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.689s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 5.45 / 11  (49.5):   4%|▍         | 11/252 [01:29<28:38,  7.13s/it]

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 5.65 / 12  (47.1):   5%|▍         | 12/252 [01:33<25:15,  6.31s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.331999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.98s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.752s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}
Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 5.75 / 13  (44.2):   5%|▌         | 13/252 [01:43<28:42,  7.21s/it]INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.561s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.855s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 5.949999999999999 / 15  (39.7):   6%|▌         | 15/252 [01:56<25:47,  6.53s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.492s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.449999999999999 / 16  (40.3):   6%|▋         | 16/252 [02:03<26:32,  6.75s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.513s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.622s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.3 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.908s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 7.449999999999999 / 17  (43.8):   7%|▋         | 17/252 [02:10<26:09,  6.68s/it]INFO:backoff:Backing off request(...) for 106.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.471s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.443s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 106.6 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 35.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.47s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 35.3 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 9.15 / 19  (48.2):   8%|▊         | 19/252 [02:24<24:46,  6.38s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 10.25 / 21  (48.8):   8%|▊         | 21/252 [02:37<24:32,  6.38s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 10.6 / 22  (48.2):   9%|▊         | 22/252 [02:47<27:41,  7.23s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.712s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 11.4 / 23  (49.6):   9%|▉         | 23/252 [02:56<29:45,  7.80s/it]INFO:backoff:Backing off request(...) for 43.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.769s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 43.6 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.782s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.987s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 12.65 / 27  (46.9):  11%|█         | 27/252 [03:21<24:15,  6.47s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 13.1 / 28  (46.8):  11%|█         | 28/252 [03:31<27:34,  7.39s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 13.9 / 29  (47.9):  12%|█▏        | 29/252 [03:38<26:38,  7.17s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.8 / 30  (49.3):  12%|█▏        | 30/252 [03:45<26:21,  7.12s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.395s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.781s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.931s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 14.9 / 31  (48.1):  12%|█▏        | 31/252 [03:49<23:13,  6.30s/it]

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.0 / 32  (46.9):  13%|█▎        | 32/252 [03:56<23:28,  6.40s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.588s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.85 / 33  (48.0):  13%|█▎        | 33/252 [04:02<23:41,  6.49s/it]INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.436s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 244.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.39s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 244.1 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.83s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.88s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 16.4 / 34  (48.2):  13%|█▎        | 34/252 [04:13<28:42,  7.90s/it]

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.588s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.997s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 17.25 / 35  (49.3):  14%|█▍        | 35/252 [04:18<24:51,  6.87s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.295s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 17.6 / 36  (48.9):  14%|█▍        | 36/252 [04:29<29:41,  8.25s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.791s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.848s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.869s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 17.8 / 37  (48.1):  15%|█▍        | 37/252 [04:38<30:11,  8.42s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.784s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.447s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.629s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 18.2 / 38  (47.9):  15%|█▌        | 38/252 [04:50<34:05,  9.56s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.483s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 18.55 / 39  (47.6):  15%|█▌        | 39/252 [04:56<29:57,  8.44s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.865s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 19.05 / 40  (47.6):  16%|█▌        | 40/252 [05:03<27:52,  7.89s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.774s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.917s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 19.55 / 41  (47.7):  16%|█▋        | 41/252 [05:05<21:48,  6.20s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.537s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.918s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.55 / 42  (48.9):  17%|█▋        | 42/252 [05:16<26:53,  7.68s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.514s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.900000000000002 / 43  (48.6):  17%|█▋        | 43/252 [05:19<21:12,  6.09s/it]INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.484999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.929s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.400000000000002 / 44  (48.6):  17%|█▋        | 44/252 [05:30<26:37,  7.68s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.476999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.973s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.900000000000002 / 45  (48.7):  18%|█▊        | 45/252 [05:34<23:06,  6.70s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.879s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.3 / 46  (48.5):  18%|█▊        | 46/252 [05:37<18:26,  5.37s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.65s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.978s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.8 / 48  (47.5):  19%|█▉        | 48/252 [05:50<19:27,  5.72s/it]INFO:backoff:Backing off request(...) for 6.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.346s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.0 / 49  (46.9):  19%|█▉        | 49/252 [05:59<22:38,  6.69s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.626s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.924s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.6 / 50  (47.2):  20%|█▉        | 50/252 [06:06<22:48,  6.77s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.648s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.0 / 51  (47.1):  20%|██        | 51/252 [06:17<27:03,  8.08s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 24.0 / 52  (46.2):  21%|██        | 52/252 [06:20<21:02,  6.31s/it]

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.945s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 24.1 / 53  (45.5):  21%|██        | 53/252 [06:26<21:21,  6.44s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.519s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.841s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.200000000000003 / 54  (44.8):  21%|██▏       | 54/252 [06:36<23:57,  7.26s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.848s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.62s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.874s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 24.700000000000003 / 55  (44.9):  22%|██▏       | 55/252 [06:45<26:05,  7.95s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.658s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.865s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.200000000000003 / 56  (45.0):  22%|██▏       | 56/252 [06:50<22:47,  6.98s/it]INFO:backoff:Backing off request(...) for 4.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.779s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.633s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 25.400000000000002 / 57  (44.6):  23%|██▎       | 57/252 [07:04<29:31,  9.08s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.8 / 58  (44.5):  23%|██▎       | 58/252 [07:06<22:46,  7.05s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.69s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.97s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 26.7 / 59  (45.3):  23%|██▎       | 59/252 [07:15<24:30,  7.62s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.484s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.639s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 27.2 / 60  (45.3):  24%|██▍       | 60/252 [07:22<23:50,  7.45s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.972s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 27.3 / 61  (44.8):  24%|██▍       | 61/252 [07:29<23:08,  7.27s/it]

Backing off 0.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.586s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.66s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 27.55 / 63  (43.7):  25%|██▌       | 63/252 [07:43<22:18,  7.08s/it]INFO:backoff:Backing off request(...) for 17.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.374s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 17.6 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 28.35 / 64  (44.3):  25%|██▌       | 64/252 [07:47<19:47,  6.31s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.3 / 66  (44.4):  26%|██▌       | 66/252 [08:04<22:22,  7.22s/it]INFO:backoff:Backing off request(...) for 45.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.642s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 45.7 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.8 / 67  (44.5):  27%|██▋       | 67/252 [08:11<21:38,  7.02s/it]INFO:backoff:Backing off request(...) for 337.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.283s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 337.3 seconds after 10 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.976s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.3 / 68  (44.6):  27%|██▋       | 68/252 [08:18<21:30,  7.01s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 31.75 / 71  (44.7):  28%|██▊       | 71/252 [08:43<24:00,  7.96s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.803s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 31.95 / 72  (44.4):  29%|██▊       | 72/252 [08:50<22:48,  7.60s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.724s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.986s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 32.800000000000004 / 74  (44.3):  29%|██▉       | 74/252 [09:04<21:14,  7.16s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.899s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 32.900000000000006 / 75  (43.9):  30%|██▉       | 75/252 [09:08<18:42,  6.34s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.991s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.41s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.873s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 33.7 / 76  (44.3):  30%|███       | 76/252 [09:22<25:14,  8.61s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.531s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.050000000000004 / 77  (44.2):  31%|███       | 77/252 [09:24<19:15,  6.60s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.463s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.699s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.400000000000006 / 78  (44.1):  31%|███       | 78/252 [09:29<17:44,  6.12s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.627s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.60000000000001 / 79  (43.8):  31%|███▏      | 79/252 [09:34<16:02,  5.56s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.637s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.939s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.982s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.973s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.650000000000006 / 80  (43.3):  32%|███▏      | 80/252 [09:48<23:14,  8.11s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.981s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 35.00000000000001 / 81  (43.2):  32%|███▏      | 81/252 [09:54<22:02,  7.73s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 35.35000000000001 / 82  (43.1):  33%|███▎      | 82/252 [09:57<17:07,  6.05s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.849s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.994s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 35.85000000000001 / 83  (43.2):  33%|███▎      | 83/252 [10:08<21:25,  7.61s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.519s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 36.650000000000006 / 84  (43.6):  33%|███▎      | 84/252 [10:10<16:43,  5.97s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.35s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.452999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.406s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.35000000000001 / 86  (43.4):  34%|███▍      | 86/252 [10:24<16:13,  5.86s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.468s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.400000000000006 / 87  (43.0):  35%|███▍      | 87/252 [10:30<16:45,  6.09s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.813s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.643s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.2 / 88  (43.4):  35%|███▍      | 88/252 [10:40<20:02,  7.33s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.509s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.993s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.550000000000004 / 89  (43.3):  35%|███▌      | 89/252 [10:46<18:36,  6.85s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.92s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 39.050000000000004 / 90  (43.4):  36%|███▌      | 90/252 [10:48<14:50,  5.50s/it]

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.821s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.767s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.908s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 39.550000000000004 / 91  (43.5):  36%|███▌      | 91/252 [11:00<19:21,  7.21s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.98s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.812s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.150000000000006 / 93  (43.2):  37%|███▋      | 93/252 [11:13<17:17,  6.52s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.827s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.728s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.75000000000001 / 95  (42.9):  38%|███▊      | 95/252 [11:27<16:28,  6.30s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.787s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.768s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.95000000000001 / 96  (42.7):  38%|███▊      | 96/252 [11:34<16:52,  6.49s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.515s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.75000000000001 / 97  (43.0):  38%|███▊      | 97/252 [11:40<16:53,  6.54s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.668s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.337s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.699s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 42.25000000000001 / 98  (43.1):  39%|███▉      | 98/252 [11:49<18:42,  7.29s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.947s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 42.60000000000001 / 99  (43.0):  39%|███▉      | 99/252 [12:01<21:41,  8.51s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.515s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 42.60000000000001 / 100  (42.6):  40%|███▉      | 100/252 [12:03<16:41,  6.59s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 43.35000000000001 / 101  (42.9):  40%|████      | 101/252 [12:08<15:07,  6.01s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.851s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.616s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 43.95000000000001 / 103  (42.7):  41%|████      | 103/252 [12:23<15:55,  6.41s/it]INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.604s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.901s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.771s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.85000000000001 / 104  (43.1):  41%|████▏     | 104/252 [12:33<18:01,  7.31s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.05000000000001 / 105  (42.9):  42%|████▏     | 105/252 [12:39<17:34,  7.17s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.776s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.902s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.10000000000001 / 106  (42.5):  42%|████▏     | 106/252 [12:51<20:17,  8.34s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.899s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.90000000000001 / 108  (42.5):  43%|████▎     | 108/252 [12:57<13:46,  5.74s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.311s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.40000000000001 / 109  (42.6):  43%|████▎     | 109/252 [13:06<16:01,  6.72s/it]INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 47.20000000000001 / 110  (42.9):  44%|████▎     | 110/252 [13:13<15:50,  6.69s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 47.60000000000001 / 111  (42.9):  44%|████▍     | 111/252 [13:18<14:15,  6.07s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.48s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.928s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.05000000000001 / 112  (42.9):  44%|████▍     | 112/252 [13:25<15:02,  6.45s/it]INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.156s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 48.55000000000001 / 113  (43.0):  45%|████▍     | 113/252 [13:34<16:47,  7.25s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.528s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.946s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.00000000000001 / 115  (42.6):  46%|████▌     | 115/252 [13:46<14:07,  6.18s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.502s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 189.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.419s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 189.2 seconds after 11 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.400000000000006 / 116  (42.6):  46%|████▌     | 116/252 [13:55<16:09,  7.13s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.616s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.60000000000001 / 117  (42.4):  46%|████▋     | 117/252 [14:00<14:14,  6.33s/it]INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.60000000000001 / 118  (42.9):  47%|████▋     | 118/252 [14:11<17:24,  7.79s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.493s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.856s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.70000000000001 / 119  (42.6):  47%|████▋     | 119/252 [14:17<16:27,  7.42s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.691s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.827s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 51.10000000000001 / 120  (42.6):  48%|████▊     | 120/252 [14:24<15:44,  7.16s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.897s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.634s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 51.7 / 122  (42.4):  48%|████▊     | 122/252 [14:35<13:12,  6.09s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 51.800000000000004 / 123  (42.1):  49%|████▉     | 123/252 [14:40<12:04,  5.62s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.537s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 52.300000000000004 / 124  (42.2):  49%|████▉     | 124/252 [14:49<14:21,  6.73s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.463s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 52.35 / 125  (41.9):  50%|████▉     | 125/252 [14:56<14:23,  6.80s/it]INFO:backoff:Backing off request(...) for 7.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.511s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 52.65 / 126  (41.8):  50%|█████     | 126/252 [15:05<15:36,  7.43s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 15.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.938s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 15.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.35 / 128  (41.7):  51%|█████     | 128/252 [15:16<12:52,  6.23s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.991s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.75 / 129  (41.7):  51%|█████     | 129/252 [15:24<13:23,  6.53s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.85 / 130  (41.4):  52%|█████▏    | 130/252 [15:33<14:56,  7.35s/it]INFO:backoff:Backing off request(...) for 7.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.65 / 132  (42.2):  52%|█████▏    | 132/252 [15:46<13:59,  7.00s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.618s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.874s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.85 / 133  (42.0):  53%|█████▎    | 133/252 [15:57<16:25,  8.28s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.468999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.95 / 134  (41.8):  53%|█████▎    | 134/252 [16:00<12:40,  6.45s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.85 / 135  (42.1):  54%|█████▎    | 135/252 [16:07<12:59,  6.66s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.596s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.92s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 57.85 / 136  (42.5):  54%|█████▍    | 136/252 [16:15<13:57,  7.22s/it]

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.95 / 137  (42.3):  54%|█████▍    | 137/252 [16:18<11:01,  5.75s/it]INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.462s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.98s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.819s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.623s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 58.300000000000004 / 138  (42.2):  55%|█████▍    | 138/252 [16:34<16:46,  8.83s/it]

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.7s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.663s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.1 / 139  (42.5):  55%|█████▌    | 139/252 [16:38<14:15,  7.58s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.9 / 140  (42.8):  56%|█████▌    | 140/252 [16:42<12:11,  6.53s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.535s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.396s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.902s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 60.3 / 141  (42.8):  56%|█████▌    | 141/252 [16:49<12:16,  6.64s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.976s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.349999999999994 / 142  (42.5):  56%|█████▋    | 142/252 [16:58<13:29,  7.36s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.367s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.851s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.449999999999996 / 143  (42.3):  57%|█████▋    | 143/252 [17:03<11:55,  6.56s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.978s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 60.65 / 144  (42.1):  57%|█████▋    | 144/252 [17:05<09:20,  5.19s/it]

Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.618s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.442s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.452999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.199999999999996 / 145  (42.2):  58%|█████▊    | 145/252 [17:14<11:25,  6.41s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.742s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 61.4 / 146  (42.1):  58%|█████▊    | 146/252 [17:19<10:17,  5.82s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.956s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.8s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 25.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.432s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 25.4 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.6 / 148  (41.6):  59%|█████▊    | 148/252 [17:33<10:20,  5.97s/it]INFO:backoff:Backing off request(...) for 10.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.478s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 62.1 / 149  (41.7):  59%|█████▉    | 149/252 [17:44<12:54,  7.52s/it]INFO:backoff:Backing off request(...) for 33.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.482s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.418s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 33.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 62.6 / 150  (41.7):  60%|█████▉    | 150/252 [17:48<11:21,  6.68s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.71s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.942s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 63.050000000000004 / 151  (41.8):  60%|█████▉    | 151/252 [18:04<15:49,  9.40s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.721s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 63.95 / 153  (41.8):  61%|██████    | 153/252 [18:08<09:24,  5.70s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.596s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.705s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.64999999999999 / 155  (41.7):  62%|██████▏   | 155/252 [18:22<09:27,  5.85s/it]INFO:backoff:Backing off request(...) for 7.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 67.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.408s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 67.8 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.74999999999999 / 156  (41.5):  62%|██████▏   | 156/252 [18:34<12:04,  7.55s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.81s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.69999999999999 / 157  (41.2):  62%|██████▏   | 157/252 [18:38<10:19,  6.52s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.569s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.46s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.19999999999999 / 158  (41.3):  63%|██████▎   | 158/252 [18:53<14:30,  9.26s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.496s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.24999999999999 / 159  (41.0):  63%|██████▎   | 159/252 [18:56<11:28,  7.40s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.918s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.52s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.34999999999998 / 160  (40.8):  63%|██████▎   | 160/252 [19:07<12:39,  8.26s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.753s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.501s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.539s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 66.19999999999997 / 161  (41.1):  64%|██████▍   | 161/252 [19:14<12:04,  7.96s/it]

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.69999999999997 / 162  (41.2):  64%|██████▍   | 162/252 [19:18<10:11,  6.80s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.708s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.595s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.502s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 66.74999999999997 / 163  (41.0):  65%|██████▍   | 163/252 [19:25<10:10,  6.86s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.79999999999997 / 164  (40.7):  65%|██████▌   | 164/252 [19:32<09:55,  6.77s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.637s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.901s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.819s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.419s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.765s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.34999999999997 / 165  (40.8):  65%|██████▌   | 165/252 [19:41<10:49,  7.47s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.856s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.689s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.69999999999996 / 166  (40.8):  66%|██████▌   | 166/252 [19:49<11:16,  7.87s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.588s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.496s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.89999999999996 / 167  (40.7):  66%|██████▋   | 167/252 [19:52<08:43,  6.16s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.37s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.608s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.849s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.19999999999996 / 169  (40.9):  67%|██████▋   | 169/252 [20:05<08:22,  6.05s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.702s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.624s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 14.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.906s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 69.24999999999996 / 170  (40.7):  67%|██████▋   | 170/252 [20:12<08:32,  6.25s/it]

Backing off 14.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.749s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.742s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.547s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.909s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.951s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.761s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.982s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 69.74999999999996 / 171  (40.8):  68%|██████▊   | 171/252 [20:31<13:40, 10.13s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.935s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.84999999999995 / 172  (40.6):  68%|██████▊   | 172/252 [20:38<12:05,  9.07s/it]INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.601999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.742s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.345s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.34999999999995 / 173  (40.7):  69%|██████▊   | 173/252 [20:42<10:07,  7.69s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.974s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.19999999999995 / 174  (40.9):  69%|██████▉   | 174/252 [20:49<09:33,  7.35s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 71.29999999999994 / 175  (40.7):  69%|██████▉   | 175/252 [20:51<07:28,  5.82s/it]

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.292s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.834s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.777s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.732s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 72.29999999999994 / 177  (40.8):  70%|███████   | 177/252 [21:07<07:50,  6.27s/it]INFO:backoff:Backing off request(...) for 2.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.482s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.319s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.985s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.09999999999994 / 178  (41.1):  71%|███████   | 178/252 [21:18<09:33,  7.75s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.878s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.501s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.29999999999994 / 179  (40.9):  71%|███████   | 179/252 [21:20<07:22,  6.06s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.327s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.281s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.534s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 74.09999999999994 / 180  (41.2):  71%|███████▏  | 180/252 [21:29<08:20,  6.95s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.964s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.827s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.692s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.879s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 74.59999999999994 / 181  (41.2):  72%|███████▏  | 181/252 [21:40<09:41,  8.19s/it]

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 75.59999999999994 / 182  (41.5):  72%|███████▏  | 182/252 [21:42<07:25,  6.36s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.417s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.395s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.672s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.943s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.881s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 76.39999999999993 / 183  (41.7):  73%|███████▎  | 183/252 [21:51<08:15,  7.18s/it]

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.89999999999993 / 184  (41.8):  73%|███████▎  | 184/252 [21:53<06:27,  5.69s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.742s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.448s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 77.24999999999993 / 185  (41.8):  73%|███████▎  | 185/252 [22:05<08:13,  7.36s/it]INFO:backoff:Backing off request(...) for 6.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.657s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 6.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 77.64999999999993 / 186  (41.7):  74%|███████▍  | 186/252 [22:07<06:33,  5.97s/it]

Backing off 6.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 6.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.714s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 78.14999999999993 / 187  (41.8):  74%|███████▍  | 187/252 [22:16<07:18,  6.75s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.234999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.849s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.79s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.14999999999993 / 188  (42.1):  75%|███████▍  | 188/252 [22:23<07:13,  6.78s/it]INFO:backoff:Backing off request(...) for 11.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.59s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.493s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.929s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.791s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.64999999999993 / 189  (42.1):  75%|███████▌  | 189/252 [22:30<07:13,  6.88s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.862s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.69999999999993 / 190  (41.9):  75%|███████▌  | 190/252 [22:35<06:24,  6.20s/it]INFO:backoff:Backing off request(...) for 5.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.777s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.996s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 108.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.854s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 108.0 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.89999999999993 / 191  (41.8):  76%|███████▌  | 191/252 [22:41<06:29,  6.39s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.997s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 80.79999999999994 / 192  (42.1):  76%|███████▌  | 192/252 [22:46<05:49,  5.82s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.466s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.924s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 80.99999999999994 / 193  (42.0):  77%|███████▋  | 193/252 [22:57<07:25,  7.55s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.869s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 81.39999999999995 / 194  (42.0):  77%|███████▋  | 194/252 [23:02<06:23,  6.62s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.41s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 81.99999999999994 / 195  (42.1):  77%|███████▋  | 195/252 [23:13<07:35,  8.00s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.691s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.39999999999995 / 196  (42.0):  78%|███████▊  | 196/252 [23:15<05:50,  6.26s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.656s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.44999999999995 / 197  (41.9):  78%|███████▊  | 197/252 [23:27<07:06,  7.75s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.303s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.54999999999994 / 198  (41.7):  79%|███████▊  | 198/252 [23:29<05:30,  6.12s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.651s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 83.34999999999994 / 199  (41.9):  79%|███████▉  | 199/252 [23:31<04:24,  5.00s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.552s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.939s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.44999999999993 / 200  (41.7):  79%|███████▉  | 200/252 [23:40<05:15,  6.06s/it]INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.808s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.281s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.54999999999993 / 201  (41.6):  80%|███████▉  | 201/252 [23:49<05:51,  6.89s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.767s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.816s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.64999999999992 / 202  (41.4):  80%|████████  | 202/252 [23:58<06:16,  7.52s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.379s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 84.44999999999992 / 203  (41.6):  81%|████████  | 203/252 [24:00<04:51,  5.95s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.918s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.861s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 84.69999999999992 / 204  (41.5):  81%|████████  | 204/252 [24:07<05:00,  6.26s/it]

Backing off 6.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.19999999999992 / 205  (41.6):  81%|████████▏ | 205/252 [24:14<05:05,  6.49s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.616s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.665s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 16.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.633s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 16.0 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.985s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.79999999999993 / 207  (41.4):  82%|████████▏ | 207/252 [24:30<05:28,  7.30s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.754s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 20.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.619s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 20.5 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.558s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.856s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 86.24999999999993 / 208  (41.5):  83%|████████▎ | 208/252 [24:40<05:51,  7.99s/it]

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 93.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.48s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 93.8 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.964s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 87.04999999999993 / 209  (41.7):  83%|████████▎ | 209/252 [24:47<05:28,  7.64s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.865s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.867s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 87.49999999999993 / 210  (41.7):  83%|████████▎ | 210/252 [24:58<06:08,  8.78s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.480999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.39999999999993 / 211  (41.9):  84%|████████▎ | 211/252 [25:01<04:42,  6.89s/it]INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.946s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.59999999999994 / 212  (41.8):  84%|████████▍ | 212/252 [25:07<04:33,  6.84s/it]INFO:backoff:Backing off request(...) for 7.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.925s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.54999999999993 / 214  (41.8):  85%|████████▍ | 214/252 [25:21<04:03,  6.40s/it]INFO:backoff:Backing off request(...) for 9.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.307s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 9.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.537s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 89.94999999999993 / 215  (41.8):  85%|████████▌ | 215/252 [25:35<05:17,  8.57s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 90.29999999999993 / 216  (41.8):  86%|████████▌ | 216/252 [25:37<03:59,  6.65s/it]INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.331999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.54999999999993 / 218  (42.0):  87%|████████▋ | 218/252 [25:50<03:33,  6.28s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.847s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.818s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 92.34999999999992 / 219  (42.2):  87%|████████▋ | 219/252 [25:57<03:30,  6.37s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.633s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 93.14999999999992 / 220  (42.3):  87%|████████▋ | 220/252 [26:04<03:28,  6.51s/it]

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.617s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 93.19999999999992 / 221  (42.2):  88%|████████▊ | 221/252 [26:10<03:22,  6.53s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.946s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 12.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.278s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 12.0 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 93.59999999999992 / 222  (42.2):  88%|████████▊ | 222/252 [26:17<03:21,  6.71s/it]INFO:backoff:Backing off request(...) for 249.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 249.4 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}
Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 93.94999999999992 / 223  (42.1):  88%|████████▊ | 223/252 [26:24<03:16,  6.77s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 94.84999999999992 / 224  (42.3):  89%|████████▉ | 224/252 [26:31<03:07,  6.69s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.804s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.544s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.91s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 94.94999999999992 / 225  (42.2):  89%|████████▉ | 225/252 [26:44<03:55,  8.72s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 95.94999999999992 / 226  (42.5):  90%|████████▉ | 226/252 [26:47<02:57,  6.81s/it]INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.496s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.89s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 96.04999999999991 / 227  (42.3):  90%|█████████ | 227/252 [26:56<03:06,  7.45s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.275s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.4s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 96.54999999999991 / 228  (42.3):  90%|█████████ | 228/252 [27:05<03:10,  7.94s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.34999999999991 / 229  (42.5):  91%|█████████ | 229/252 [27:07<02:22,  6.21s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.346s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.421s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.04999999999991 / 231  (42.4):  92%|█████████▏| 231/252 [27:20<02:07,  6.08s/it]INFO:backoff:Backing off request(...) for 5.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.553s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.846s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.974s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 98.24999999999991 / 232  (42.3):  92%|█████████▏| 232/252 [27:31<02:31,  7.58s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 98.69999999999992 / 233  (42.4):  92%|█████████▏| 233/252 [27:36<02:06,  6.66s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.841s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.565s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.876s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 98.64999999999992 / 234  (42.2):  93%|█████████▎| 234/252 [27:45<02:13,  7.43s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.375s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.99999999999991 / 235  (42.1):  93%|█████████▎| 235/252 [27:52<02:05,  7.36s/it]INFO:backoff:Backing off request(...) for 5.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.668s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 13.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.91s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 99.44999999999992 / 236  (42.1):  94%|█████████▎| 236/252 [28:01<02:05,  7.87s/it]

Backing off 13.9 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 99.84999999999992 / 237  (42.1):  94%|█████████▍| 237/252 [28:04<01:34,  6.32s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.862s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.64999999999992 / 238  (42.3):  94%|█████████▍| 238/252 [28:11<01:29,  6.41s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.635s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.74999999999991 / 239  (42.2):  95%|█████████▍| 239/252 [28:16<01:17,  5.93s/it]INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.677s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 101.09999999999991 / 240  (42.1):  95%|█████████▌| 240/252 [28:22<01:13,  6.15s/it]INFO:backoff:Backing off request(...) for 4.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.779s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 101.8999999999999 / 241  (42.3):  96%|█████████▌| 241/252 [28:34<01:24,  7.70s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.374s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.603s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 101.9999999999999 / 242  (42.1):  96%|█████████▌| 242/252 [28:41<01:14,  7.49s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.638s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.844s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.3499999999999 / 243  (42.1):  96%|█████████▋| 243/252 [28:45<00:59,  6.58s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.479s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.64999999999989 / 244  (42.1):  97%|█████████▋| 244/252 [28:56<01:03,  7.96s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.475s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 103.0999999999999 / 245  (42.1):  97%|█████████▋| 245/252 [28:59<00:44,  6.35s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.537s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.947s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 103.39999999999989 / 246  (42.0):  98%|█████████▊| 246/252 [29:10<00:46,  7.81s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.43s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 104.0999999999999 / 247  (42.1):  98%|█████████▊| 247/252 [29:17<00:37,  7.50s/it]INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.561s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 104.44999999999989 / 248  (42.1):  98%|█████████▊| 248/252 [29:23<00:29,  7.27s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.705s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.509s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 105.54999999999988 / 250  (42.2):  99%|█████████▉| 250/252 [29:32<00:11,  5.64s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.468s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 105.69999999999987 / 252  (41.9): 100%|██████████| 252/252 [30:32<00:00,  7.27s/it]
  2%|▏         | 4/252 [00:04<04:52,  1.18s/it]
Average Metric: 1.2999999999999998 / 3  (43.3):   1%|          | 3/252 [00:03<05:25,  1.31s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 2.1999999999999997 / 4  (55.0):   2%|▏         | 4/252 [00:06<06:50,  1.65s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.528s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.522s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.446s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.68s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.767s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 2.6999999999999997 / 5  (54.0):   2%|▏         | 5/252 [00:17<20:07,  4.89s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.981s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.906s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.561s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 3.1999999999999997 / 6  (53.3):   2%|▏         | 6/252 [00:27<26:03,  6.36s/it]

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.347s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 3.1999999999999997 / 7  (45.7):   3%|▎         | 7/252 [00:28<19:56,  4.88s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.52s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.515s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.832s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.535s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 3.5999999999999996 / 8  (45.0):   3%|▎         | 8/252 [00:38<25:23,  6.24s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.402s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.498s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.493s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 4.1 / 9  (45.6):   4%|▎         | 9/252 [00:44<25:51,  6.39s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.964s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.645s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.904s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 4.55 / 10  (45.5):   4%|▍         | 10/252 [00:53<28:03,  6.96s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.917s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 5.05 / 11  (45.9):   4%|▍         | 11/252 [00:56<23:37,  5.88s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.577s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.523s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 5.95 / 12  (49.6):   5%|▍         | 12/252 [01:08<30:23,  7.60s/it]

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.662s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.965s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.45 / 13  (49.6):   5%|▌         | 13/252 [01:14<29:03,  7.30s/it]INFO:backoff:Backing off request(...) for 10.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.277s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.024999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.95 / 14  (49.6):   6%|▌         | 14/252 [01:16<22:36,  5.70s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.458s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.743s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 2s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.794s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 7.45 / 15  (49.7):   6%|▌         | 15/252 [01:28<29:31,  7.48s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.775s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.543s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.435s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 7.55 / 16  (47.2):   6%|▋         | 16/252 [01:34<28:26,  7.23s/it]INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.791s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.782s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.702s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 8.45 / 17  (49.7):   7%|▋         | 17/252 [01:41<27:55,  7.13s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.694s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.542s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.896s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 8.95 / 18  (49.7):   7%|▋         | 18/252 [01:48<27:15,  6.99s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.459s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.101s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.531s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.986s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.65s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 9.85 / 19  (51.8):   8%|▊         | 19/252 [01:55<27:01,  6.96s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.625s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.588s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 10.65 / 20  (53.2):   8%|▊         | 20/252 [01:59<23:51,  6.17s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 11.15 / 21  (53.1):   8%|▊         | 21/252 [02:01<19:07,  4.97s/it]INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.291s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.548s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.513s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.945s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 11.25 / 22  (51.1):   9%|▊         | 22/252 [02:13<26:19,  6.87s/it]

Backing off 0.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.784s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.55s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.933s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 12.25 / 23  (53.3):   9%|▉         | 23/252 [02:20<26:22,  6.91s/it]

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.711s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.881s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 13.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 13.7 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 12.3 / 24  (51.2):  10%|▉         | 24/252 [02:27<26:25,  6.95s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.911s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 13.100000000000001 / 25  (52.4):  10%|▉         | 25/252 [02:31<23:28,  6.21s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.479s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.588s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.876s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.000000000000002 / 26  (53.8):  10%|█         | 26/252 [02:41<27:08,  7.20s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.378s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.748s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.400000000000002 / 27  (53.3):  11%|█         | 27/252 [02:47<26:27,  7.06s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 12.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.711s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 12.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.506s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.427s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.350000000000001 / 28  (51.3):  11%|█         | 28/252 [03:02<34:15,  9.18s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.895s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.697s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 14.400000000000002 / 29  (49.7):  12%|█▏        | 29/252 [03:06<29:00,  7.80s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.499s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.800000000000002 / 30  (49.3):  12%|█▏        | 30/252 [03:08<22:20,  6.04s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.878s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.150000000000002 / 31  (48.9):  12%|█▏        | 31/252 [03:13<21:20,  5.79s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.862s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.897s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.601s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.250000000000002 / 32  (47.7):  13%|█▎        | 32/252 [03:22<24:35,  6.71s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.201s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.650000000000002 / 33  (47.4):  13%|█▎        | 33/252 [03:29<24:36,  6.74s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.559s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.611s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.561s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.05 / 34  (47.2):  13%|█▎        | 34/252 [03:40<29:43,  8.18s/it]INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.813s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.387s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.45 / 35  (47.0):  14%|█▍        | 35/252 [03:43<23:16,  6.43s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.99s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.816s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.649s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.55 / 36  (46.0):  14%|█▍        | 36/252 [03:52<25:53,  7.19s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.767s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.816s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 17.45 / 37  (47.2):  15%|█▍        | 37/252 [03:54<20:58,  5.85s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.515s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 17.849999999999998 / 38  (47.0):  15%|█▌        | 38/252 [04:04<24:31,  6.88s/it]

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.283s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 18.349999999999998 / 39  (47.1):  15%|█▌        | 39/252 [04:08<21:20,  6.01s/it]INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.583s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.46s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.971s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 18.849999999999998 / 40  (47.1):  16%|█▌        | 40/252 [04:14<21:57,  6.22s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.188s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.572s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.565s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 19.849999999999998 / 42  (47.3):  17%|█▋        | 42/252 [04:28<21:20,  6.10s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.338s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.924s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 6.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.78s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 6.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.349999999999998 / 43  (47.3):  17%|█▋        | 43/252 [04:40<27:14,  7.82s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.588s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.832s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.442s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.527s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.349999999999998 / 45  (47.4):  18%|█▊        | 45/252 [04:52<21:59,  6.38s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.991s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.653s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.2 / 46  (48.3):  18%|█▊        | 46/252 [04:58<22:14,  6.48s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.531s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.836s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.911s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.852s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.55 / 48  (47.0):  19%|█▉        | 48/252 [05:12<21:01,  6.18s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.271s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.25s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.650000000000002 / 49  (46.2):  19%|█▉        | 49/252 [05:19<21:40,  6.41s/it]INFO:backoff:Backing off request(...) for 4.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.593s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.554s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.05 / 50  (46.1):  20%|█▉        | 50/252 [05:26<22:25,  6.66s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.679s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.728s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.657s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.45 / 52  (45.1):  21%|██        | 52/252 [05:39<20:41,  6.21s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.533s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.349s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.936s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 23.65 / 53  (44.6):  21%|██        | 53/252 [05:44<18:52,  5.69s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.873s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.806s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.15 / 54  (44.7):  21%|██▏       | 54/252 [05:57<26:46,  8.11s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.987s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.549999999999997 / 55  (44.6):  22%|██▏       | 55/252 [06:02<22:42,  6.92s/it]INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.657s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.568s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.65 / 56  (44.0):  22%|██▏       | 56/252 [06:04<18:14,  5.59s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.692s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.754s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.933s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 24.75 / 57  (43.4):  23%|██▎       | 57/252 [06:13<21:51,  6.72s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.378s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.85 / 58  (42.8):  23%|██▎       | 58/252 [06:18<19:25,  6.01s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.35 / 59  (43.0):  23%|██▎       | 59/252 [06:25<20:11,  6.28s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.331s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.173s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.305s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 26.200000000000003 / 60  (43.7):  24%|██▍       | 60/252 [06:31<19:57,  6.24s/it]INFO:backoff:Backing off request(...) for 7.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.573s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.965s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.904s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 26.700000000000003 / 61  (43.8):  24%|██▍       | 61/252 [06:42<24:30,  7.70s/it]

Backing off 5.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.567s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 26.800000000000004 / 62  (43.2):  25%|██▍       | 62/252 [06:48<23:20,  7.37s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 27.250000000000004 / 63  (43.3):  25%|██▌       | 63/252 [06:51<18:13,  5.79s/it]INFO:backoff:Backing off request(...) for 21.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.699s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 21.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.193s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.747s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.786s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 27.200000000000003 / 64  (42.5):  25%|██▌       | 64/252 [07:00<21:19,  6.81s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.707s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.561s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.502s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 28.1 / 65  (43.2):  26%|██▌       | 65/252 [07:07<21:48,  7.00s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.747s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.505s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 28.200000000000003 / 66  (42.7):  26%|██▌       | 66/252 [07:16<23:32,  7.59s/it]INFO:backoff:Backing off request(...) for 51.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.694s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 51.1 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.642s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 29.1 / 67  (43.4):  27%|██▋       | 67/252 [07:21<20:33,  6.67s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.6 / 68  (43.5):  27%|██▋       | 68/252 [07:23<16:14,  5.29s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.981s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.439s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.0 / 69  (43.5):  27%|██▋       | 69/252 [07:32<20:11,  6.62s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.782s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.543s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.763s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.5 / 70  (43.6):  28%|██▊       | 70/252 [07:42<22:49,  7.52s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.958s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.7 / 71  (43.2):  28%|██▊       | 71/252 [07:51<23:59,  7.95s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.623s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.978s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 31.55 / 72  (43.8):  29%|██▊       | 72/252 [07:58<23:15,  7.75s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.878s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.618s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 31.75 / 73  (43.5):  29%|██▉       | 73/252 [08:03<20:15,  6.79s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 31.95 / 74  (43.2):  29%|██▉       | 74/252 [08:10<20:05,  6.77s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.654s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 21.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 21.5 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 32.45 / 75  (43.3):  30%|██▉       | 75/252 [08:16<19:49,  6.72s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.662s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 33.7 / 77  (43.8):  31%|███       | 77/252 [08:28<17:17,  5.93s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.353s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.743s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.150000000000006 / 78  (43.8):  31%|███       | 78/252 [08:37<20:02,  6.91s/it]INFO:backoff:Backing off request(...) for 52.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.268s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 52.8 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.50000000000001 / 79  (43.7):  31%|███▏      | 79/252 [08:44<19:54,  6.91s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.765s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.633s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.991s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 34.550000000000004 / 80  (43.2):  32%|███▏      | 80/252 [08:48<17:46,  6.20s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.651s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 35.050000000000004 / 81  (43.3):  32%|███▏      | 81/252 [08:58<20:28,  7.18s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.857s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.827s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.88s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 35.400000000000006 / 82  (43.2):  33%|███▎      | 82/252 [09:05<20:37,  7.28s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 36.300000000000004 / 83  (43.7):  33%|███▎      | 83/252 [09:12<20:13,  7.18s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.675s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 22.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.553s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 22.3 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 36.7 / 84  (43.7):  33%|███▎      | 84/252 [09:21<21:34,  7.71s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.1 / 86  (43.1):  34%|███▍      | 86/252 [09:34<19:29,  7.05s/it]INFO:backoff:Backing off request(...) for 276.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.413s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 276.4 seconds after 10 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.6 / 87  (43.2):  35%|███▍      | 87/252 [09:41<19:17,  7.01s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.617s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.681s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.4 / 88  (43.6):  35%|███▍      | 88/252 [09:49<20:04,  7.35s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.6s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.8 / 89  (43.6):  35%|███▌      | 89/252 [09:52<16:41,  6.14s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.77s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 39.599999999999994 / 90  (44.0):  36%|███▌      | 90/252 [09:57<15:15,  5.65s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.69s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.099999999999994 / 91  (44.1):  36%|███▌      | 91/252 [10:06<18:20,  6.84s/it]INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.494s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.49999999999999 / 92  (44.0):  37%|███▋      | 92/252 [10:12<17:07,  6.42s/it]INFO:backoff:Backing off request(...) for 11.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.575s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.854s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 40.599999999999994 / 93  (43.7):  37%|███▋      | 93/252 [10:20<18:38,  7.04s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.796s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.849999999999994 / 94  (43.5):  37%|███▋      | 94/252 [10:27<18:40,  7.09s/it]INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.938s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 41.24999999999999 / 95  (43.4):  38%|███▊      | 95/252 [10:39<22:10,  8.48s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.28s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.612s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 42.04999999999999 / 96  (43.8):  38%|███▊      | 96/252 [10:44<19:33,  7.52s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.675s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 42.14999999999999 / 97  (43.5):  38%|███▊      | 97/252 [10:51<18:33,  7.19s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.869s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 42.699999999999996 / 99  (43.1):  39%|███▉      | 99/252 [11:10<21:02,  8.25s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.669s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.981s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 43.199999999999996 / 100  (43.2):  40%|███▉      | 100/252 [11:12<16:22,  6.46s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.732s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 43.24999999999999 / 101  (42.8):  40%|████      | 101/252 [11:20<17:19,  6.88s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.914s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.646s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 43.599999999999994 / 102  (42.7):  40%|████      | 102/252 [11:28<18:23,  7.36s/it]

Backing off 1.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.401s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.993s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 43.949999999999996 / 103  (42.7):  41%|████      | 103/252 [11:33<16:11,  6.52s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.592s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.349999999999994 / 104  (42.6):  41%|████▏     | 104/252 [11:39<16:14,  6.58s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.426s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.849999999999994 / 105  (42.7):  42%|████▏     | 105/252 [11:46<16:24,  6.70s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.732s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.943s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 45.74999999999999 / 106  (43.2):  42%|████▏     | 106/252 [11:54<16:42,  6.86s/it]INFO:backoff:Backing off request(...) for 8.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.774s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 8.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 45.949999999999996 / 107  (42.9):  42%|████▏     | 107/252 [11:58<14:50,  6.14s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.625s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.449999999999996 / 108  (43.0):  43%|████▎     | 108/252 [12:12<20:23,  8.50s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.745s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.947s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 47.24999999999999 / 109  (43.3):  43%|████▎     | 109/252 [12:21<20:52,  8.76s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.665s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.682s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.04999999999999 / 110  (43.7):  44%|████▎     | 110/252 [12:29<19:34,  8.27s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.692s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.632s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.636s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.962s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 48.44999999999999 / 111  (43.6):  44%|████▍     | 111/252 [12:38<20:05,  8.55s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.94999999999999 / 112  (43.7):  44%|████▍     | 112/252 [12:40<15:40,  6.72s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.836s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.699s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.89999999999999 / 114  (43.8):  45%|████▌     | 114/252 [12:54<14:42,  6.39s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.341s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.512s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 49.99999999999999 / 115  (43.5):  46%|████▌     | 115/252 [12:59<13:14,  5.80s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.394s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.987s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.951s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.917s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 50.04999999999999 / 116  (43.1):  46%|████▌     | 116/252 [13:10<17:13,  7.60s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.982s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.14999999999999 / 117  (42.9):  46%|████▋     | 117/252 [13:18<16:58,  7.55s/it]INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.64999999999999 / 118  (42.9):  47%|████▋     | 118/252 [13:24<16:17,  7.29s/it]INFO:backoff:Backing off request(...) for 6.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.635s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.64999999999999 / 119  (42.6):  47%|████▋     | 119/252 [13:34<17:49,  8.04s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.556s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 16.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.519s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 16.0 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 51.199999999999996 / 121  (42.3):  48%|████▊     | 121/252 [13:46<14:27,  6.62s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.534s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 52.24999999999999 / 123  (42.5):  49%|████▉     | 123/252 [14:00<13:31,  6.29s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.709s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.693s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.737s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.92s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 523.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 523.1 seconds after 11 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.29999999999999 / 125  (42.6):  50%|████▉     | 125/252 [14:16<14:07,  6.67s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.601s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 53.79999999999999 / 126  (42.7):  50%|█████     | 126/252 [14:19<11:28,  5.47s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.496s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.84999999999999 / 127  (42.4):  50%|█████     | 127/252 [14:29<14:47,  7.10s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.658s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.71s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.851s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 54.79999999999999 / 129  (42.5):  51%|█████     | 129/252 [14:38<11:20,  5.54s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.289s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.717s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.646s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 55.19999999999999 / 130  (42.5):  52%|█████▏    | 130/252 [14:45<12:11,  6.00s/it]

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.806s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.09999999999999 / 131  (42.8):  52%|█████▏    | 131/252 [14:54<13:56,  6.91s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.559s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.656s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.899999999999984 / 132  (43.1):  52%|█████▏    | 132/252 [15:04<15:39,  7.83s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.149999999999984 / 133  (43.0):  53%|█████▎    | 133/252 [15:09<13:29,  6.80s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.844s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.367s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.34999999999999 / 134  (42.8):  53%|█████▎    | 134/252 [15:20<15:57,  8.12s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.549s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.399999999999984 / 135  (42.5):  54%|█████▎    | 135/252 [15:22<12:17,  6.30s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.974s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.954s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 58.19999999999998 / 136  (42.8):  54%|█████▍    | 136/252 [15:31<13:43,  7.10s/it]INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.533s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 58.29999999999998 / 137  (42.6):  54%|█████▍    | 137/252 [15:34<11:02,  5.76s/it]

Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.09999999999998 / 138  (42.8):  55%|█████▍    | 138/252 [15:43<12:49,  6.75s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.63s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.51s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.88s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.14999999999998 / 139  (42.6):  55%|█████▌    | 139/252 [15:54<15:17,  8.12s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 59.549999999999976 / 140  (42.5):  56%|█████▌    | 140/252 [15:57<12:02,  6.45s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.585s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.914s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.949999999999974 / 141  (42.5):  56%|█████▌    | 141/252 [16:08<14:29,  7.83s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.625s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 60.449999999999974 / 142  (42.6):  56%|█████▋    | 142/252 [16:15<14:03,  7.66s/it]

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.49999999999997 / 143  (42.3):  57%|█████▋    | 143/252 [16:17<10:54,  6.00s/it]INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.982s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.74999999999997 / 144  (42.2):  57%|█████▋    | 144/252 [16:26<12:29,  6.94s/it]INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.654s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.45s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.99999999999997 / 145  (42.1):  58%|█████▊    | 145/252 [16:35<13:31,  7.59s/it]INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.604s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.34999999999997 / 146  (42.0):  58%|█████▊    | 146/252 [16:38<10:35,  6.00s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.986s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.554s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.699999999999974 / 147  (42.0):  58%|█████▊    | 147/252 [16:45<10:58,  6.27s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.908s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 62.199999999999974 / 148  (42.0):  59%|█████▊    | 148/252 [16:56<13:41,  7.90s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.774s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 62.699999999999974 / 149  (42.1):  59%|█████▉    | 149/252 [17:03<13:05,  7.63s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.717s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.928s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 62.89999999999998 / 150  (41.9):  60%|█████▉    | 150/252 [17:08<11:41,  6.88s/it]

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 63.84999999999998 / 152  (42.0):  60%|██████    | 152/252 [17:18<09:17,  5.58s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.272s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.419s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.769s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.7s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.411s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.44999999999997 / 153  (42.1):  61%|██████    | 153/252 [17:33<14:04,  8.53s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.725s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.64999999999998 / 154  (42.0):  61%|██████    | 154/252 [17:36<11:09,  6.83s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.748s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.856s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.29999999999998 / 156  (41.9):  62%|██████▏   | 156/252 [17:45<08:57,  5.60s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.634s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.488s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.617s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.733s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.495s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.818s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.29999999999998 / 157  (41.6):  62%|██████▏   | 157/252 [18:00<13:36,  8.59s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.574s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.24999999999999 / 158  (41.3):  63%|██████▎   | 158/252 [18:03<10:38,  6.79s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.83s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.638s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.74999999999999 / 159  (41.4):  63%|██████▎   | 159/252 [18:09<10:20,  6.67s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.783s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.462s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.54999999999998 / 160  (41.6):  63%|██████▎   | 160/252 [18:14<09:22,  6.12s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.609s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.88s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.89999999999998 / 162  (41.9):  64%|██████▍   | 162/252 [18:30<10:03,  6.71s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.595s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.752s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.94999999999997 / 163  (41.7):  65%|██████▍   | 163/252 [18:40<11:18,  7.63s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.81s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.954s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 68.79999999999998 / 165  (41.7):  65%|██████▌   | 165/252 [18:52<09:16,  6.39s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.938s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.04999999999998 / 166  (41.6):  66%|██████▌   | 166/252 [18:59<09:22,  6.54s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.808s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.632s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.963s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 69.14999999999998 / 167  (41.4):  66%|██████▋   | 167/252 [19:03<08:27,  5.97s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.19999999999997 / 168  (41.2):  67%|██████▋   | 168/252 [19:10<08:49,  6.30s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.552s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.249s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.89999999999998 / 169  (41.4):  67%|██████▋   | 169/252 [19:25<12:19,  8.90s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.309s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.202999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.89999999999998 / 171  (41.5):  68%|██████▊   | 171/252 [19:33<08:02,  5.96s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.556s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.29999999999998 / 172  (41.5):  68%|██████▊   | 172/252 [19:36<06:57,  5.22s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.917s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.801s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.568s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.49999999999999 / 173  (41.3):  69%|██████▊   | 173/252 [19:46<08:37,  6.55s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.379s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.59999999999998 / 174  (41.1):  69%|██████▉   | 174/252 [19:51<07:55,  6.09s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.455s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 72.09999999999998 / 175  (41.2):  69%|██████▉   | 175/252 [19:57<08:05,  6.31s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.440999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.636s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 72.89999999999998 / 176  (41.4):  70%|██████▉   | 176/252 [20:07<09:06,  7.19s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.79999999999998 / 177  (41.7):  70%|███████   | 177/252 [20:14<08:51,  7.09s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.384s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.311s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.818s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 74.29999999999998 / 178  (41.7):  71%|███████   | 178/252 [20:21<08:45,  7.10s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 74.64999999999998 / 179  (41.7):  71%|███████   | 179/252 [20:23<06:43,  5.53s/it]

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.728s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.899s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 75.44999999999997 / 180  (41.9):  71%|███████▏  | 180/252 [20:34<08:49,  7.35s/it]

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.44999999999997 / 181  (42.2):  72%|███████▏  | 181/252 [20:39<07:42,  6.51s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.794s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.979s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 76.89999999999998 / 182  (42.3):  72%|███████▏  | 181/252 [20:51<07:42,  6.51s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 77.69999999999997 / 183  (42.5):  73%|███████▎  | 183/252 [20:53<07:31,  6.55s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.974s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.347s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 77.94999999999997 / 184  (42.4):  73%|███████▎  | 184/252 [21:00<07:19,  6.46s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.745s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.374s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 77.94999999999997 / 185  (42.1):  73%|███████▎  | 185/252 [21:06<07:15,  6.51s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.539s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.581s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 78.39999999999998 / 186  (42.2):  74%|███████▍  | 186/252 [21:16<08:07,  7.39s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 78.39999999999998 / 187  (41.9):  74%|███████▍  | 187/252 [21:23<07:57,  7.35s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.805s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.673s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 78.84999999999998 / 188  (41.9):  75%|███████▍  | 188/252 [21:32<08:25,  7.89s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.536s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.896s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 78.79999999999998 / 189  (41.7):  75%|███████▌  | 189/252 [21:37<07:12,  6.87s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.692s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.44999999999999 / 191  (41.6):  76%|███████▌  | 191/252 [21:51<06:36,  6.49s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.752s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.977s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 80.35 / 192  (41.8):  76%|███████▌  | 192/252 [21:53<05:15,  5.25s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 81.64999999999999 / 194  (42.1):  77%|███████▋  | 194/252 [22:07<05:36,  5.80s/it]INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.519s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.28s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 81.69999999999999 / 195  (41.9):  77%|███████▋  | 195/252 [22:16<06:26,  6.78s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.19999999999999 / 196  (41.9):  78%|███████▊  | 196/252 [22:26<07:05,  7.60s/it]INFO:backoff:Backing off request(...) for 21.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.631s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 21.7 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.19999999999999 / 198  (42.0):  79%|███████▊  | 198/252 [22:39<06:07,  6.81s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.29999999999998 / 199  (41.9):  79%|███████▉  | 199/252 [22:43<05:28,  6.20s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.66s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.29999999999998 / 200  (41.6):  79%|███████▉  | 200/252 [22:55<06:44,  7.78s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.77s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.51s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.64999999999998 / 201  (41.6):  80%|███████▉  | 201/252 [23:02<06:20,  7.46s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.532s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.911s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 84.54999999999998 / 202  (41.9):  80%|████████  | 202/252 [23:14<07:20,  8.80s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.44999999999999 / 203  (42.1):  81%|████████  | 203/252 [23:18<06:06,  7.48s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.25s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.79999999999998 / 204  (42.1):  81%|████████  | 204/252 [23:29<06:58,  8.71s/it]INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.665s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.447s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.5 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.29999999999998 / 205  (42.1):  81%|████████▏ | 205/252 [23:32<05:17,  6.76s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.83s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.69999999999999 / 206  (42.1):  82%|████████▏ | 206/252 [23:41<05:47,  7.56s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.730999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 14.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.635s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 14.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.796s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.653s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 87.69999999999999 / 208  (42.2):  83%|████████▎ | 208/252 [23:52<04:34,  6.24s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.7s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.997s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 11.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.656s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.559s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 88.6 / 209  (42.4):  83%|████████▎ | 209/252 [23:59<04:40,  6.53s/it]

Backing off 11.8 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.904s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.0 / 210  (42.4):  83%|████████▎ | 210/252 [24:11<05:34,  7.97s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.516s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.916s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.1 / 211  (42.2):  84%|████████▎ | 211/252 [24:16<04:47,  7.01s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.611s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.75s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.625s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.3 / 212  (42.1):  84%|████████▍ | 212/252 [24:22<04:36,  6.90s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.725s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 90.2 / 213  (42.3):  85%|████████▍ | 213/252 [24:29<04:32,  6.99s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 9.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.648s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 9.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.916s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 90.4 / 214  (42.2):  85%|████████▍ | 214/252 [24:37<04:31,  7.14s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.674s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.25s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 90.9 / 215  (42.3):  85%|████████▌ | 215/252 [24:42<03:57,  6.41s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.747s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.358s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.546s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 90.95 / 216  (42.1):  86%|████████▌ | 216/252 [24:50<04:12,  7.01s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.843s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.75 / 217  (42.3):  86%|████████▌ | 217/252 [24:54<03:34,  6.14s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.669s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.998s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.743s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 92.25 / 218  (42.3):  87%|████████▋ | 218/252 [25:01<03:40,  6.47s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 11.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.683s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.397s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 92.5 / 219  (42.2):  87%|████████▋ | 219/252 [25:10<03:55,  7.15s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.822s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 93.35 / 220  (42.4):  87%|████████▋ | 220/252 [25:17<03:44,  7.03s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.402s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 22.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 22.8 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.438s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 93.69999999999999 / 221  (42.4):  88%|████████▊ | 221/252 [25:26<03:55,  7.61s/it]INFO:backoff:Backing off request(...) for 6.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 94.04999999999998 / 222  (42.4):  88%|████████▊ | 222/252 [25:28<02:59,  5.98s/it]

Backing off 6.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 94.94999999999999 / 223  (42.6):  88%|████████▊ | 223/252 [25:38<03:25,  7.07s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.867s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 95.35 / 224  (42.6):  89%|████████▉ | 224/252 [25:44<03:14,  6.96s/it]INFO:backoff:Backing off request(...) for 13.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.867s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 13.9 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 95.69999999999999 / 225  (42.5):  89%|████████▉ | 225/252 [25:47<02:31,  5.61s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.732s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.754s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 95.79999999999998 / 226  (42.4):  90%|████████▉ | 226/252 [25:58<03:10,  7.34s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.338s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 55.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.996s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 95.89999999999998 / 227  (42.2):  90%|█████████ | 227/252 [26:03<02:41,  6.47s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.881s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 55.2 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 96.69999999999997 / 228  (42.4):  90%|█████████ | 228/252 [26:08<02:24,  6.03s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.975s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.04999999999997 / 229  (42.4):  91%|█████████ | 229/252 [26:22<03:14,  8.47s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.67s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 97.24999999999997 / 230  (42.3):  91%|█████████▏| 230/252 [26:24<02:25,  6.59s/it]

Backing off 2.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.74999999999997 / 231  (42.3):  92%|█████████▏| 231/252 [26:26<01:51,  5.30s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.836s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.853s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.54999999999997 / 233  (42.3):  92%|█████████▏| 233/252 [26:40<01:49,  5.75s/it]INFO:backoff:Backing off request(...) for 7.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.393s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.926s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.99999999999997 / 234  (42.3):  93%|█████████▎| 234/252 [26:54<02:27,  8.18s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.71s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.94999999999997 / 235  (42.1):  93%|█████████▎| 235/252 [26:56<01:48,  6.36s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.985s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 40.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.537s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 40.9 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 99.29999999999997 / 236  (42.1):  94%|█████████▎| 236/252 [27:03<01:45,  6.60s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.831s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 99.69999999999997 / 237  (42.1):  94%|█████████▍| 237/252 [27:10<01:39,  6.65s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.622s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.542s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 100.14999999999998 / 238  (42.1):  94%|█████████▍| 238/252 [27:15<01:24,  6.04s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.916s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.631s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.94999999999997 / 239  (42.2):  95%|█████████▍| 239/252 [27:29<01:48,  8.38s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.699s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.952s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 101.39999999999998 / 240  (42.2):  95%|█████████▌| 240/252 [27:35<01:34,  7.88s/it]INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.752s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.555s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.74999999999997 / 242  (42.5):  96%|█████████▌| 242/252 [27:47<01:05,  6.51s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.689s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.559s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.909s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 103.64999999999998 / 243  (42.7):  96%|█████████▋| 243/252 [27:52<00:53,  5.96s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.337s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.611s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 104.14999999999998 / 244  (42.7):  97%|█████████▋| 244/252 [27:56<00:44,  5.52s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.565s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 104.54999999999998 / 245  (42.7):  97%|█████████▋| 245/252 [28:01<00:37,  5.31s/it]INFO:backoff:Backing off request(...) for 7.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.406s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.659s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 104.94999999999999 / 246  (42.7):  98%|█████████▊| 246/252 [28:12<00:42,  7.17s/it]INFO:backoff:Backing off request(...) for 14.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.991s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 14.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.703s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 105.14999999999999 / 247  (42.6):  98%|█████████▊| 247/252 [28:20<00:35,  7.20s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.954s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.947s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 105.35 / 248  (42.5):  98%|█████████▊| 248/252 [28:27<00:29,  7.30s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.561s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 105.55 / 249  (42.4):  99%|█████████▉| 249/252 [28:36<00:22,  7.65s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.993s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 106.55 / 250  (42.6):  99%|█████████▉| 250/252 [28:38<00:11,  5.99s/it]

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.659s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 106.64999999999999 / 251  (42.5): 100%|█████████▉| 251/252 [28:43<00:05,  5.73s/it]

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 106.74999999999999 / 252  (42.4): 100%|██████████| 252/252 [28:50<00:00,  6.87s/it]
  2%|▏         | 4/252 [00:32<33:12,  8.04s/it]
  0%|          | 0/252 [00:00<?, ?it/s]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.997s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.977s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.536s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 0.05 / 1  (5.0):   0%|          | 1/252 [00:14<59:31, 14.23s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.625s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.539s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 0.9500000000000001 / 2  (47.5):   1%|          | 2/252 [00:18<35:02,  8.41s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.836s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.212s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 1.8 / 3  (60.0):   1%|          | 3/252 [00:23<27:36,  6.65s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.484999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 2.3 / 4  (57.5):   2%|▏         | 4/252 [00:29<26:54,  6.51s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.544s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.389s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.539s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 27.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.484s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 27.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.7s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 2.6999999999999997 / 6  (45.0):   2%|▏         | 6/252 [00:45<28:00,  6.83s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.591s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.933s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 3.1999999999999997 / 7  (45.7):   3%|▎         | 7/252 [00:50<24:46,  6.07s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.753s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.832s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.656s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 3.1999999999999997 / 8  (40.0):   3%|▎         | 8/252 [01:00<29:56,  7.36s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 3.65 / 9  (40.6):   4%|▎         | 9/252 [01:06<28:56,  7.15s/it]INFO:backoff:Backing off request(...) for 49.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.37s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 49.0 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 4.15 / 10  (41.5):   4%|▍         | 10/252 [01:09<22:39,  5.62s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.836s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.554s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.507s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 5.15 / 12  (42.9):   5%|▍         | 12/252 [01:23<24:00,  6.00s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.699s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.59s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.050000000000001 / 13  (46.5):   5%|▌         | 13/252 [01:34<29:48,  7.48s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.743s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.674s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.550000000000001 / 14  (46.8):   6%|▌         | 14/252 [01:41<28:52,  7.28s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.796s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.456999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.65 / 15  (44.3):   6%|▌         | 15/252 [01:45<25:19,  6.41s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.783s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.434s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 7.65 / 16  (47.8):   6%|▋         | 16/252 [01:57<31:18,  7.96s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.91s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 14.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.238999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 14.4 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.942s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 7.65 / 17  (45.0):   7%|▋         | 17/252 [02:01<27:02,  6.91s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.972s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 8.450000000000001 / 18  (46.9):   7%|▋         | 18/252 [02:08<27:13,  6.98s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.665s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.679s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 9.450000000000001 / 19  (49.7):   8%|▊         | 19/252 [02:20<32:28,  8.36s/it]

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.853s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 10.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.784s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 10.0 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 10.350000000000001 / 20  (51.8):   8%|▊         | 20/252 [02:27<30:24,  7.86s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 10.850000000000001 / 21  (51.7):   8%|▊         | 21/252 [02:36<32:34,  8.46s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 11.250000000000002 / 23  (48.9):   9%|▉         | 23/252 [02:41<19:50,  5.20s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.541s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.648s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.506s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.686s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 11.300000000000002 / 24  (47.1):  10%|▉         | 24/252 [02:50<24:31,  6.45s/it]

Backing off 0.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.92s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.673s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 11.250000000000002 / 25  (45.0):  10%|▉         | 25/252 [02:57<24:58,  6.60s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.43s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.628s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.68s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 15.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 11.300000000000002 / 26  (43.5):  10%|█         | 26/252 [03:04<24:48,  6.59s/it]

Backing off 15.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.59s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 12.200000000000003 / 27  (45.2):  11%|█         | 27/252 [03:10<25:06,  6.70s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.359999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.977s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 12.250000000000004 / 28  (43.8):  11%|█         | 28/252 [03:15<22:37,  6.06s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.881s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.965s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 12.600000000000003 / 29  (43.4):  12%|█▏        | 29/252 [03:24<26:16,  7.07s/it]

Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.516s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.977s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.749s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 13.000000000000004 / 30  (43.3):  12%|█▏        | 30/252 [03:34<28:39,  7.75s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.701s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.482s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 13.500000000000004 / 31  (43.5):  12%|█▏        | 31/252 [03:38<24:35,  6.68s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.603s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.693s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.516s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.444999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 13.600000000000003 / 32  (42.5):  13%|█▎        | 32/252 [03:47<26:49,  7.32s/it]

Backing off 4.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.397s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.958s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 13.950000000000003 / 33  (42.3):  13%|█▎        | 33/252 [03:54<26:12,  7.18s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.342s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.997s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.350000000000003 / 34  (42.2):  13%|█▎        | 34/252 [03:58<23:22,  6.43s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.593999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.939s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.831s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 14.800000000000002 / 35  (42.3):  14%|█▍        | 35/252 [04:06<24:08,  6.67s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.926s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.419s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.972s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 15.000000000000002 / 36  (41.7):  14%|█▍        | 36/252 [04:15<26:41,  7.41s/it]

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.771s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.347999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.986s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.400000000000002 / 37  (41.6):  15%|█▍        | 37/252 [04:24<28:27,  7.94s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.750000000000002 / 38  (41.4):  15%|█▌        | 38/252 [04:26<22:22,  6.27s/it]INFO:backoff:Backing off request(...) for 11.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.769s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.795s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.25 / 39  (41.7):  15%|█▌        | 39/252 [04:37<26:35,  7.49s/it]INFO:backoff:Backing off request(...) for 4.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.47s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.987s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.862s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.25 / 40  (40.6):  16%|█▌        | 40/252 [04:45<27:07,  7.68s/it]INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.39s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.943s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.65 / 41  (40.6):  16%|█▋        | 41/252 [04:51<26:00,  7.40s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.534s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 17.15 / 42  (40.8):  17%|█▋        | 42/252 [04:56<22:41,  6.48s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.834s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.495s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.593s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.589s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 17.5 / 43  (40.7):  17%|█▋        | 43/252 [05:05<25:50,  7.42s/it]INFO:backoff:Backing off request(...) for 7.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.503s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.767s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.909s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 18.0 / 44  (40.9):  17%|█▋        | 44/252 [05:12<24:52,  7.18s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.480999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 19.0 / 45  (42.2):  18%|█▊        | 45/252 [05:17<22:33,  6.54s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.965s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.847s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.4 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.327999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 19.0 / 46  (41.3):  18%|█▊        | 45/252 [05:26<22:33,  6.54s/it]INFO:backoff:Backing off request(...) for 17.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 19.0 / 46  (41.3):  18%|█▊        | 46/252 [05:26<25:04,  7.31s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 17.5 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 19.1 / 47  (40.6):  19%|█▊        | 47/252 [05:33<24:25,  7.15s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.865s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.581s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.669s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.803s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 19.950000000000003 / 48  (41.6):  19%|█▉        | 48/252 [05:44<28:44,  8.45s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.724s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 44.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.638s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 20.450000000000003 / 49  (41.7):  19%|█▉        | 49/252 [05:47<22:37,  6.69s/it]

Backing off 44.3 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.691s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.717s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.650000000000002 / 50  (41.3):  20%|█▉        | 50/252 [05:56<24:52,  7.39s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.652s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.05 / 51  (41.3):  20%|██        | 51/252 [05:58<19:36,  5.85s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.758s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.55 / 52  (41.4):  21%|██        | 52/252 [06:05<20:34,  6.17s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.757s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.701s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.721s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 21.95 / 53  (41.4):  21%|██        | 53/252 [06:13<21:37,  6.52s/it]

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.427s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.899s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 22.45 / 54  (41.6):  21%|██▏       | 54/252 [06:22<24:10,  7.32s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.507s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 22.95 / 55  (41.7):  22%|██▏       | 55/252 [06:24<19:07,  5.83s/it]INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.655s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.5 / 56  (42.0):  22%|██▏       | 56/252 [06:31<20:08,  6.16s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 4.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.736s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 4.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.9 / 57  (41.9):  23%|██▎       | 57/252 [06:36<18:34,  5.72s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.209s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.0 / 58  (41.4):  23%|██▎       | 58/252 [06:43<19:34,  6.05s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.521s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.455s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.487s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.617s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 13.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.862s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 24.9 / 59  (42.2):  23%|██▎       | 59/252 [06:51<21:54,  6.81s/it]

Backing off 13.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.452999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.349999999999998 / 60  (42.2):  24%|██▍       | 60/252 [06:58<21:41,  6.78s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.299s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.775s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.642s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.883s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.349999999999998 / 61  (41.6):  24%|██▍       | 61/252 [07:07<24:11,  7.60s/it]INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.6s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.649s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.955s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 25.45 / 62  (41.0):  25%|██▍       | 62/252 [07:14<23:18,  7.36s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.55 / 63  (40.6):  25%|██▌       | 63/252 [07:16<18:21,  5.83s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.339s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.971s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.997s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.647s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.911s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 25.75 / 64  (40.2):  25%|██▌       | 64/252 [07:28<23:41,  7.56s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.776s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 26.65 / 65  (41.0):  26%|██▌       | 65/252 [07:35<23:16,  7.47s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.862s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.725s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 27.549999999999997 / 66  (41.7):  26%|██▌       | 66/252 [07:42<22:36,  7.29s/it]

Backing off 1.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.787s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 13.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.603s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 13.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 28.049999999999997 / 67  (41.9):  27%|██▋       | 67/252 [07:47<20:04,  6.51s/it]INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 28.449999999999996 / 68  (41.8):  27%|██▋       | 68/252 [07:56<22:21,  7.29s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.652s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.315999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.784s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.634s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 28.399999999999995 / 69  (41.2):  27%|██▋       | 69/252 [08:05<23:58,  7.86s/it]

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.994s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 28.499999999999996 / 70  (40.7):  28%|██▊       | 70/252 [08:07<18:39,  6.15s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.952s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.742s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.965s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.858s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.299999999999997 / 72  (40.7):  29%|██▊       | 72/252 [08:19<16:37,  5.54s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.56s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.218s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.319s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.652s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 29.499999999999996 / 73  (40.4):  29%|██▉       | 73/252 [08:28<19:57,  6.69s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.738s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.999999999999996 / 74  (40.5):  29%|██▉       | 74/252 [08:35<20:11,  6.81s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.559s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.657s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.349999999999998 / 75  (40.5):  30%|██▉       | 75/252 [08:42<20:24,  6.92s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.54s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.549999999999997 / 76  (40.2):  30%|███       | 76/252 [08:46<17:48,  6.07s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.582s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.466s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.609s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 31.449999999999996 / 77  (40.8):  31%|███       | 77/252 [08:56<20:23,  6.99s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.804s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.509s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.409s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.37s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.629s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 31.849999999999994 / 78  (40.8):  31%|███       | 78/252 [09:05<21:57,  7.57s/it]INFO:backoff:Backing off request(...) for 8.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.413s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 32.05 / 79  (40.6):  31%|███▏      | 79/252 [09:07<17:08,  5.95s/it]INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.546s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 12.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 32.4 / 80  (40.5):  32%|███▏      | 80/252 [09:18<21:45,  7.59s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.79s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 12.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.75s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.968s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.397s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 32.85 / 81  (40.6):  32%|███▏      | 81/252 [09:28<23:21,  8.20s/it]

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 32.9 / 82  (40.1):  33%|███▎      | 82/252 [09:28<16:27,  5.81s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.286s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.186s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.412s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 33.25 / 83  (40.1):  33%|███▎      | 83/252 [09:35<17:22,  6.17s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.339999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.15 / 84  (40.7):  33%|███▎      | 84/252 [09:46<21:04,  7.53s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.955s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.874s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.199999999999996 / 85  (40.2):  34%|███▎      | 85/252 [09:53<20:23,  7.33s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.775s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.474s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.599999999999994 / 86  (40.2):  34%|███▍      | 86/252 [09:55<15:50,  5.73s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 35.099999999999994 / 87  (40.3):  35%|███▍      | 87/252 [10:01<16:34,  6.03s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.502s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.746s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.335999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.421s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.319s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.771s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.65s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 35.599999999999994 / 88  (40.5):  35%|███▍      | 87/252 [10:13<16:34,  6.03s/it]INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.492s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 35.599999999999994 / 88  (40.5):  35%|███▍      | 88/252 [10:13<21:13,  7.76s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.842s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.993s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 36.099999999999994 / 89  (40.6):  35%|███▌      | 89/252 [10:20<20:11,  7.43s/it]

Backing off 4.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.47s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.749s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.92s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.69s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 36.3 / 90  (40.3):  36%|███▌      | 90/252 [10:36<27:05, 10.03s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.251s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 36.699999999999996 / 91  (40.3):  36%|███▌      | 91/252 [10:38<20:19,  7.58s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.619s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.65s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.099999999999994 / 92  (40.3):  37%|███▋      | 92/252 [10:44<19:34,  7.34s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.524s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.774s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.666s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.599999999999994 / 93  (40.4):  37%|███▋      | 93/252 [10:52<19:16,  7.28s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.515s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.699999999999996 / 94  (40.1):  37%|███▋      | 94/252 [10:54<14:57,  5.68s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.562s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.98s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.099999999999994 / 95  (40.1):  38%|███▊      | 95/252 [11:03<17:27,  6.67s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.467s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.49999999999999 / 96  (40.1):  38%|███▊      | 96/252 [11:05<13:56,  5.36s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.246s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.406s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.849999999999994 / 97  (40.1):  38%|███▊      | 97/252 [11:12<14:52,  5.76s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.23s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.717s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.613s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.538s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.641s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 39.349999999999994 / 98  (40.2):  39%|███▉      | 98/252 [11:21<17:51,  6.95s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.993s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.669s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 39.349999999999994 / 99  (39.7):  39%|███▉      | 99/252 [11:30<19:15,  7.55s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.474s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.437s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.918s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.956s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.854s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 39.599999999999994 / 100  (39.6):  40%|███▉      | 100/252 [11:44<23:59,  9.47s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.099999999999994 / 101  (39.7):  40%|████      | 101/252 [11:46<18:19,  7.28s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.645s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.834s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 40.199999999999996 / 102  (39.4):  40%|████      | 102/252 [11:51<16:09,  6.46s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.77s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.484999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.985s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.599999999999994 / 103  (39.4):  41%|████      | 103/252 [12:00<17:53,  7.20s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.513s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.479s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.993s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.617s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 40.99999999999999 / 104  (39.4):  41%|████▏     | 104/252 [12:09<19:08,  7.76s/it]INFO:backoff:Backing off request(...) for 5.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.501s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 5.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.199999999999996 / 105  (39.2):  42%|████▏     | 105/252 [12:12<15:19,  6.25s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.283s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.699999999999996 / 106  (39.3):  42%|████▏     | 106/252 [12:18<15:17,  6.28s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.666s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 11.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.436s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.3 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.604s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.26s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 41.9 / 107  (39.2):  42%|████▏     | 107/252 [12:27<17:15,  7.14s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.675s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.708s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.583s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 62.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 62.6 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.558s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 42.75 / 109  (39.2):  43%|████▎     | 109/252 [12:39<14:33,  6.11s/it]INFO:backoff:Backing off request(...) for 5.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 43.25 / 110  (39.3):  44%|████▎     | 110/252 [12:50<18:29,  7.81s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.05 / 111  (39.7):  44%|████▍     | 111/252 [12:57<17:42,  7.53s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.648s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.918s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.544s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.449999999999996 / 112  (39.7):  44%|████▍     | 112/252 [13:06<18:35,  7.97s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.775s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.949999999999996 / 113  (39.8):  45%|████▍     | 113/252 [13:10<15:49,  6.83s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.837s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.968s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 44.9 / 114  (39.4):  45%|████▌     | 114/252 [13:16<14:42,  6.39s/it]

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.806s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.85 / 115  (39.0):  46%|████▌     | 115/252 [13:21<14:00,  6.14s/it]INFO:backoff:Backing off request(...) for 5.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.964s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.0 / 117  (38.5):  46%|████▋     | 117/252 [13:34<13:19,  5.92s/it]INFO:backoff:Backing off request(...) for 8.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.543s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.4 / 118  (38.5):  47%|████▋     | 118/252 [13:41<13:53,  6.22s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.388s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.644s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.78s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 45.9 / 119  (38.6):  47%|████▋     | 119/252 [13:52<17:00,  7.68s/it]

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.987s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 46.1 / 120  (38.4):  48%|████▊     | 120/252 [13:55<13:20,  6.07s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.857s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.796s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.965s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.298s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.2 / 121  (38.2):  48%|████▊     | 121/252 [14:03<15:06,  6.92s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.791s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.748s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.869s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.6 / 122  (38.2):  48%|████▊     | 122/252 [14:08<13:43,  6.34s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.66s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.821s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.908s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.928s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.95 / 123  (38.2):  49%|████▉     | 123/252 [14:22<18:15,  8.49s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.593999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.741s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 47.050000000000004 / 124  (37.9):  49%|████▉     | 124/252 [14:29<17:12,  8.07s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 47.25000000000001 / 125  (37.8):  50%|████▉     | 125/252 [14:36<16:19,  7.71s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.337s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.494s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 15.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.55s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 47.650000000000006 / 126  (37.8):  50%|█████     | 126/252 [14:41<14:23,  6.85s/it]

Backing off 15.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 47.650000000000006 / 127  (37.5):  50%|█████     | 127/252 [14:43<11:24,  5.47s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.050000000000004 / 128  (37.5):  51%|█████     | 128/252 [14:55<15:08,  7.33s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.508s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.45 / 129  (37.6):  51%|█████     | 129/252 [15:00<13:33,  6.61s/it]INFO:backoff:Backing off request(...) for 19.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.818s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 19.8 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.987s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.686s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.35 / 130  (38.0):  52%|█████▏    | 130/252 [15:11<16:16,  8.01s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.858s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.463s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.949999999999996 / 132  (38.6):  52%|█████▏    | 132/252 [15:22<12:55,  6.46s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.45s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.298s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 51.4 / 133  (38.6):  53%|█████▎    | 133/252 [15:27<11:45,  5.93s/it]INFO:backoff:Backing off request(...) for 6.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.202s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.77s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 52.25 / 135  (38.7):  54%|█████▎    | 135/252 [15:36<09:42,  4.98s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.762s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.939s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 52.65 / 136  (38.7):  54%|█████▍    | 136/252 [15:45<12:12,  6.32s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.947s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.839s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.818s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 52.75 / 137  (38.5):  54%|█████▍    | 137/252 [15:52<12:17,  6.41s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.55 / 138  (38.8):  55%|█████▍    | 138/252 [15:58<12:20,  6.50s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.812s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.851s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.877s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 53.8 / 139  (38.7):  55%|█████▌    | 139/252 [16:05<12:18,  6.53s/it]

Backing off 0.2 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.97s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.6 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 54.599999999999994 / 140  (39.0):  56%|█████▌    | 140/252 [16:12<12:15,  6.56s/it]INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.176s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.689s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.628s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 119.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.563s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 119.3 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.05 / 141  (39.0):  56%|█████▌    | 141/252 [16:23<14:56,  8.08s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.25 / 142  (38.9):  56%|█████▋    | 142/252 [16:25<11:33,  6.31s/it]INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.5s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.642s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 55.85 / 144  (38.8):  57%|█████▋    | 144/252 [16:39<11:00,  6.11s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.361s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.747s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.1 / 145  (38.7):  58%|█████▊    | 145/252 [16:46<11:17,  6.33s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.372s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.45 / 146  (38.7):  58%|█████▊    | 146/252 [16:53<11:31,  6.53s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.487s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.650000000000006 / 147  (38.5):  58%|█████▊    | 147/252 [16:59<11:31,  6.58s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.403s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.753s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.676s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.050000000000004 / 148  (38.5):  59%|█████▊    | 148/252 [17:11<14:01,  8.09s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.488s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.45 / 149  (38.6):  59%|█████▉    | 149/252 [17:13<10:47,  6.28s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.576s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 57.85 / 150  (38.6):  60%|█████▉    | 150/252 [17:21<11:20,  6.67s/it]

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.843s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 58.35 / 151  (38.6):  60%|█████▉    | 151/252 [17:27<11:10,  6.64s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.711s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.406s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.977s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

Average Metric: 58.300000000000004 / 152  (38.4):  60%|██████    | 152/252 [17:37<12:38,  7.59s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.99s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.752s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {'max_tokens': 75, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 58.50000000000001 / 153  (38.2):  61%|██████    | 153/252 [17:47<13:33,  8.22s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.783s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.795s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 58.85000000000001 / 154  (38.2):  61%|██████    | 154/252 [17:51<11:36,  7.11s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.945s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.659s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.30000000000001 / 155  (38.3):  62%|██████▏   | 155/252 [18:03<13:36,  8.42s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.654s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.40000000000001 / 156  (38.1):  62%|██████▏   | 156/252 [18:09<12:38,  7.90s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.46s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.90000000000001 / 157  (38.2):  62%|██████▏   | 157/252 [18:12<09:47,  6.18s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.277s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.956s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.945s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.000000000000014 / 158  (38.0):  63%|██████▎   | 158/252 [18:24<12:33,  8.02s/it]INFO:backoff:Backing off request(...) for 26.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.611s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 26.2 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.05000000000001 / 159  (37.8):  63%|██████▎   | 159/252 [18:29<10:51,  7.01s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.44s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.85000000000001 / 160  (38.0):  63%|██████▎   | 160/252 [18:33<09:38,  6.29s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.775s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.539s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.868s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.609s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 61.35000000000001 / 161  (38.1):  64%|██████▍   | 161/252 [18:43<10:54,  7.20s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.866s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.60000000000001 / 162  (38.0):  64%|██████▍   | 162/252 [18:49<10:33,  7.04s/it]INFO:backoff:Backing off request(...) for 4.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 62.60000000000001 / 163  (38.4):  65%|██████▍   | 163/252 [18:56<10:19,  6.96s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.688s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.597999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 8.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.701s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.973s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 63.05000000000001 / 164  (38.4):  65%|██████▌   | 164/252 [19:03<10:10,  6.94s/it]

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 22.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.956s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 22.9 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 63.55000000000001 / 166  (38.3):  66%|██████▌   | 166/252 [19:14<08:38,  6.02s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.367s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.777s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.819s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.868s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 63.80000000000001 / 167  (38.2):  66%|██████▋   | 167/252 [19:28<11:48,  8.34s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.841s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.844s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.20000000000002 / 168  (38.2):  67%|██████▋   | 168/252 [19:31<09:14,  6.60s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.496s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.30000000000001 / 169  (38.0):  67%|██████▋   | 169/252 [19:40<10:07,  7.32s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.773s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.881s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.819s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.15 / 170  (38.3):  67%|██████▋   | 170/252 [19:44<08:53,  6.50s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.794s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.52s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.668s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.65 / 171  (38.4):  68%|██████▊   | 171/252 [19:53<09:45,  7.23s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.531s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.15 / 172  (38.5):  68%|██████▊   | 172/252 [19:56<07:39,  5.74s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.746s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 5.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.701s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 5.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.65 / 173  (38.5):  69%|██████▊   | 173/252 [20:02<07:56,  6.03s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.39s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.498s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.480999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.7 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.656s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.75 / 174  (38.4):  69%|██████▉   | 174/252 [20:12<09:08,  7.03s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.868s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.899s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.25 / 175  (38.4):  69%|██████▉   | 175/252 [20:19<09:00,  7.02s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.821s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 4.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 4.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.821s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.75 / 176  (38.5):  70%|██████▉   | 176/252 [20:28<09:46,  7.72s/it]INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.413s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 68.0 / 177  (38.4):  70%|███████   | 177/252 [20:30<07:26,  5.95s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.857s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.266s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.713s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.601999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 68.95 / 179  (38.5):  71%|███████   | 179/252 [20:41<06:45,  5.55s/it]INFO:backoff:Backing off request(...) for 4.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.432s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.216s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.914s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.666s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.67s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.693s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.817s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.65 / 180  (38.7):  71%|███████▏  | 180/252 [21:00<11:12,  9.35s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 70.45 / 181  (38.9):  72%|███████▏  | 181/252 [21:02<08:33,  7.23s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.214s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.8 / 182  (38.9):  72%|███████▏  | 182/252 [21:06<07:26,  6.38s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.681s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.85 / 183  (38.7):  73%|███████▎  | 183/252 [21:08<05:52,  5.11s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.413s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.975s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.44s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 70.89999999999999 / 184  (38.5):  73%|███████▎  | 184/252 [21:15<06:24,  5.65s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.774s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.738s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.413s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.555s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.24999999999999 / 185  (38.5):  73%|███████▎  | 185/252 [21:25<07:30,  6.73s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.804s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.929s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.855s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.368s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.74999999999999 / 186  (38.6):  74%|███████▍  | 186/252 [21:33<08:05,  7.35s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.711s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.595s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 72.04999999999998 / 187  (38.5):  74%|███████▍  | 187/252 [21:38<07:12,  6.65s/it]

Backing off 5.7 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 72.14999999999998 / 188  (38.4):  75%|███████▍  | 188/252 [21:45<07:05,  6.65s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.839s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 36.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.689s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 36.6 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.04999999999998 / 189  (38.7):  75%|███████▌  | 189/252 [21:52<07:04,  6.74s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.471s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.468999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 72.99999999999999 / 190  (38.4):  75%|███████▌  | 190/252 [21:59<07:02,  6.81s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.753s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.839s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.761s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.74999999999999 / 192  (38.4):  76%|███████▌  | 192/252 [22:11<05:55,  5.93s/it]INFO:backoff:Backing off request(...) for 13.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.942s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 13.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.431s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 74.24999999999999 / 193  (38.5):  77%|███████▋  | 193/252 [22:20<06:52,  6.99s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 74.84999999999998 / 194  (38.6):  77%|███████▋  | 194/252 [22:25<06:02,  6.26s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 83.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.282s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 83.0 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 30.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.46s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 30.5 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 75.39999999999998 / 196  (38.5):  78%|███████▊  | 196/252 [22:38<05:38,  6.04s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.896s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 75.49999999999997 / 197  (38.3):  78%|███████▊  | 197/252 [22:48<06:32,  7.14s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.39999999999998 / 198  (38.6):  79%|███████▊  | 198/252 [22:55<06:25,  7.13s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.49999999999997 / 199  (38.4):  79%|███████▉  | 199/252 [23:02<06:12,  7.02s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.851s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.968s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 53.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 76.89999999999998 / 200  (38.4):  79%|███████▉  | 200/252 [23:09<06:09,  7.11s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 53.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.955s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.89999999999998 / 201  (38.3):  80%|███████▉  | 201/252 [23:16<05:59,  7.06s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 78.19999999999999 / 203  (38.5):  81%|████████  | 203/252 [23:27<04:51,  5.94s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.325s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.756s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.04999999999998 / 205  (38.6):  81%|████████▏ | 205/252 [23:41<04:44,  6.06s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.952s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.54999999999998 / 206  (38.6):  82%|████████▏ | 206/252 [23:53<05:56,  7.75s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.695s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.629s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.942s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 80.89999999999999 / 208  (38.9):  83%|████████▎ | 208/252 [24:07<05:05,  6.95s/it]INFO:backoff:Backing off request(...) for 68.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.482s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 68.5 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 80.94999999999999 / 209  (38.7):  83%|████████▎ | 209/252 [24:11<04:26,  6.20s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.833s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.56s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 81.35 / 210  (38.7):  83%|████████▎ | 210/252 [24:21<05:01,  7.18s/it]INFO:backoff:Backing off request(...) for 3.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 82.25 / 211  (39.0):  84%|████████▎ | 211/252 [24:25<04:20,  6.34s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.639s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.857s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.45 / 212  (38.9):  84%|████████▍ | 212/252 [24:37<05:22,  8.06s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.826s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.65 / 213  (38.8):  85%|████████▍ | 213/252 [24:43<04:43,  7.28s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.88s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.756s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.15 / 214  (38.9):  85%|████████▍ | 214/252 [24:49<04:26,  7.00s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.499s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.65 / 215  (38.9):  85%|████████▌ | 215/252 [24:53<03:50,  6.22s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.874s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.848s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 84.0 / 216  (38.9):  86%|████████▌ | 216/252 [25:00<03:52,  6.46s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.756s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.795s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.756s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 84.75 / 218  (38.9):  87%|████████▋ | 218/252 [25:14<03:35,  6.34s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.418s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.929s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.638s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 168.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.397s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 168.7 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.3 / 219  (38.9):  87%|████████▋ | 219/252 [25:21<03:30,  6.38s/it]INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.6s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.35 / 220  (38.8):  87%|████████▋ | 220/252 [25:30<03:50,  7.20s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.779s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.6 / 221  (38.7):  88%|████████▊ | 221/252 [25:37<03:38,  7.05s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.65s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 85.64999999999999 / 222  (38.6):  88%|████████▊ | 222/252 [25:44<03:31,  7.04s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.904s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.958s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.5 / 224  (38.6):  89%|████████▉ | 224/252 [25:53<02:36,  5.60s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.325s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.916s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.938s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.6 / 225  (38.5):  89%|████████▉ | 225/252 [26:04<03:16,  7.29s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.483s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.3 / 227  (38.9):  90%|█████████ | 227/252 [26:15<02:33,  6.16s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.546s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.914s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.39999999999999 / 228  (38.8):  90%|█████████ | 228/252 [26:24<02:47,  6.96s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.74999999999999 / 229  (38.8):  91%|█████████ | 229/252 [26:31<02:41,  7.00s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.662s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.529s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.826s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 89.24999999999999 / 230  (38.8):  91%|█████████▏| 230/252 [26:36<02:19,  6.33s/it]

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.534s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.612s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.44999999999999 / 231  (38.7):  92%|█████████▏| 231/252 [26:45<02:30,  7.15s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.625s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.581s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.85 / 232  (38.7):  92%|█████████▏| 232/252 [26:52<02:21,  7.07s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.553s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 90.44999999999999 / 233  (38.8):  92%|█████████▏| 233/252 [26:57<01:59,  6.30s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.772s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 90.64999999999999 / 234  (38.7):  93%|█████████▎| 234/252 [27:04<01:57,  6.51s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.182s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.373s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.1 / 235  (38.8):  93%|█████████▎| 235/252 [27:10<01:49,  6.46s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.551s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.14999999999999 / 236  (38.6):  94%|█████████▎| 236/252 [27:17<01:46,  6.67s/it]INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.55 / 237  (38.6):  94%|█████████▍| 237/252 [27:24<01:40,  6.70s/it]INFO:backoff:Backing off request(...) for 5.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.378s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.949s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 92.35 / 238  (38.8):  94%|█████████▍| 238/252 [27:33<01:42,  7.35s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.363999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.523s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 92.85 / 239  (38.8):  95%|█████████▍| 239/252 [27:42<01:43,  7.98s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 93.25 / 240  (38.9):  95%|█████████▌| 240/252 [27:49<01:32,  7.67s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.929s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 98.15 / 241  (40.7):  96%|█████████▌| 241/252 [27:51<01:05,  6.00s/it]

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.92s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.79s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.25 / 242  (40.6):  96%|█████████▌| 242/252 [28:03<01:17,  7.72s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.45s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.65 / 243  (40.6):  96%|█████████▋| 243/252 [28:07<01:00,  6.71s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.779s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.956s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.754s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 98.7 / 244  (40.5):  97%|█████████▋| 244/252 [28:17<01:00,  7.53s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.703s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.869s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.193s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.535s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.327s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 99.60000000000001 / 245  (40.7):  97%|█████████▋| 245/252 [28:26<00:55,  7.94s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.247s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.937s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.572s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.761s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.907s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 100.00000000000001 / 246  (40.7):  98%|█████████▊| 246/252 [28:32<00:45,  7.54s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.694s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.40000000000002 / 247  (40.6):  98%|█████████▊| 247/252 [28:35<00:29,  5.99s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.745s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.663s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.382s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.60000000000002 / 248  (40.6):  98%|█████████▊| 248/252 [28:41<00:24,  6.16s/it]INFO:backoff:Backing off request(...) for 6.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.505s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.673s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.649s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.95000000000002 / 249  (40.5):  99%|█████████▉| 249/252 [28:48<00:19,  6.40s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.685s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 101.95000000000002 / 250  (40.8):  99%|█████████▉| 250/252 [28:53<00:11,  5.95s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.787s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 13.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.857s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 13.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.65 / 252  (40.7): 100%|██████████| 252/252 [29:11<00:00,  6.95s/it]
  1%|          | 2/252 [00:10<20:59,  5.04s/it]
  0%|          | 0/252 [00:00<?, ?it/s]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.97s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.79s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.858s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.883s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 0.8 / 1  (80.0):   0%|          | 1/252 [00:13<57:38, 13.78s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.905s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 0.9 / 2  (45.0):   0%|          | 1/252 [00:13<57:38, 13.78s/it]

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.914s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.547s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 1.8 / 3  (60.0):   1%|          | 3/252 [00:22<28:22,  6.84s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.855s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.511s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.57s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.459s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.665s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.213s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 2.25 / 4  (56.2):   2%|▏         | 4/252 [00:36<38:01,  9.20s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.284s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 2.45 / 5  (49.0):   2%|▏         | 5/252 [00:40<30:57,  7.52s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.568s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.281s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.619s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 2.85 / 6  (47.5):   2%|▏         | 6/252 [00:47<29:49,  7.27s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 3.35 / 7  (47.9):   3%|▎         | 7/252 [00:49<22:50,  5.59s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.777s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.777s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.480999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 3.85 / 8  (48.1):   3%|▎         | 8/252 [00:56<24:29,  6.02s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.874s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.812s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.748s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.635s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.571s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 4.05 / 9  (45.0):   4%|▎         | 9/252 [01:02<25:27,  6.29s/it]

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.339s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.798s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 4.25 / 10  (42.5):   4%|▍         | 10/252 [01:09<25:43,  6.38s/it]

Backing off 2.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.448s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.915s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.578s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.758s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 4.35 / 11  (39.5):   4%|▍         | 11/252 [01:21<32:10,  8.01s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.460999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.338s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 4.55 / 12  (37.9):   5%|▍         | 12/252 [01:23<24:54,  6.23s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.993s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.928s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.679s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.571s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.541s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.972s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 4.75 / 13  (36.5):   5%|▌         | 13/252 [01:37<33:41,  8.46s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.54s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.572s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 5.65 / 14  (40.4):   6%|▌         | 14/252 [01:43<31:38,  7.98s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.579s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.8s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.65 / 15  (44.3):   6%|▌         | 15/252 [01:54<34:07,  8.64s/it]INFO:backoff:Backing off request(...) for 18.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.226s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 18.5 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 6.75 / 16  (42.2):   6%|▋         | 16/252 [01:56<26:41,  6.79s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.39s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.313s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 8.25 / 18  (45.8):   7%|▋         | 18/252 [02:04<20:08,  5.16s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.556s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.63s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.567s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 8.85 / 19  (46.6):   8%|▊         | 19/252 [02:18<30:08,  7.76s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.534s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.825s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.425s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 9.65 / 20  (48.2):   8%|▊         | 20/252 [02:24<28:25,  7.35s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.763s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.627s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.759s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.722s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 10.55 / 21  (50.2):   8%|▊         | 21/252 [02:33<30:35,  7.95s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.204s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.89s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.946s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 11.0 / 22  (50.0):   9%|▊         | 22/252 [02:40<28:59,  7.56s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.778s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 11.05 / 23  (48.0):   9%|▉         | 23/252 [02:42<22:35,  5.92s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.511s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.803s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 12.05 / 24  (50.2):  10%|▉         | 24/252 [02:45<18:33,  4.88s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.355999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.649s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.746s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 12.100000000000001 / 25  (48.4):  10%|▉         | 25/252 [02:54<23:16,  6.15s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.591s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 5.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 5.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.98s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 13.000000000000002 / 26  (50.0):  10%|█         | 26/252 [03:01<24:47,  6.58s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.663s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.363999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 13.800000000000002 / 27  (51.1):  11%|█         | 27/252 [03:10<26:51,  7.16s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.45s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.300000000000002 / 28  (51.1):  11%|█         | 28/252 [03:15<23:52,  6.39s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.684s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.417s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.5 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.471s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.750000000000002 / 29  (50.9):  12%|█▏        | 29/252 [03:24<26:58,  7.26s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.866s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 14.800000000000002 / 30  (49.3):  12%|█▏        | 30/252 [03:30<26:11,  7.08s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.845s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.881s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 60.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.447s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 60.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.150000000000002 / 31  (48.9):  12%|█▏        | 31/252 [03:35<23:34,  6.40s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.552s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 15.650000000000002 / 32  (48.9):  12%|█▏        | 31/252 [03:42<23:34,  6.40s/it]INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.832s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 15.650000000000002 / 32  (48.9):  13%|█▎        | 32/252 [03:42<23:53,  6.52s/it]

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.818s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.686s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.992s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 15.750000000000002 / 33  (47.7):  13%|█▎        | 33/252 [03:54<29:21,  8.04s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.200000000000003 / 34  (47.6):  13%|█▎        | 34/252 [03:56<22:48,  6.28s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.974s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.7s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 16.750000000000004 / 35  (47.9):  14%|█▍        | 35/252 [04:01<21:22,  5.91s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.984s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.791s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.826s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 17.600000000000005 / 36  (48.9):  14%|█▍        | 36/252 [04:10<24:27,  6.79s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.847s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.761s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 17.800000000000004 / 37  (48.1):  15%|█▍        | 37/252 [04:19<26:59,  7.53s/it]INFO:backoff:Backing off request(...) for 2.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.729s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 18.200000000000003 / 38  (47.9):  15%|█▌        | 38/252 [04:21<21:08,  5.93s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 18.700000000000003 / 39  (47.9):  15%|█▌        | 39/252 [04:31<24:49,  6.99s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.786s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 19.200000000000003 / 40  (48.0):  16%|█▌        | 40/252 [04:33<19:38,  5.56s/it]INFO:backoff:Backing off request(...) for 2.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 82.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.692s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 82.0 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.952s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 20.1 / 41  (49.0):  16%|█▋        | 41/252 [04:42<23:37,  6.72s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.841s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.811s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.894s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 20.450000000000003 / 42  (48.7):  17%|█▋        | 42/252 [04:52<26:19,  7.52s/it]

Backing off 3.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.841s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.050000000000004 / 43  (49.0):  17%|█▋        | 43/252 [05:00<27:28,  7.89s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.984s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.250000000000004 / 44  (48.3):  17%|█▋        | 44/252 [05:05<23:54,  6.89s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.805s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.876s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 21.300000000000004 / 45  (47.3):  18%|█▊        | 45/252 [05:16<28:25,  8.24s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.300000000000004 / 46  (46.3):  18%|█▊        | 46/252 [05:19<22:23,  6.52s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.793s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.785s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 21.900000000000006 / 48  (45.6):  19%|█▉        | 48/252 [05:31<19:53,  5.85s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.978s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.922s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 22.300000000000004 / 49  (45.5):  19%|█▉        | 49/252 [05:35<18:20,  5.42s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.874s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.92s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 22.500000000000004 / 50  (45.0):  20%|█▉        | 50/252 [05:47<24:42,  7.34s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.000000000000004 / 51  (45.1):  20%|██        | 51/252 [05:49<19:22,  5.78s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.877s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.78s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 23.100000000000005 / 52  (44.4):  21%|██        | 52/252 [06:00<24:53,  7.47s/it]INFO:backoff:Backing off request(...) for 16.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.487s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 16.2 seconds after 9 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.224s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 10.6 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.100000000000005 / 55  (43.8):  22%|██▏       | 55/252 [06:17<19:50,  6.04s/it]INFO:backoff:Backing off request(...) for 23.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.724s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 23.3 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.901s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.269s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.953s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.300000000000004 / 56  (43.4):  22%|██▏       | 56/252 [06:31<27:10,  8.32s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.702s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 24.400000000000006 / 57  (42.8):  23%|██▎       | 57/252 [06:33<21:09,  6.51s/it]INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.629s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.844s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 25.250000000000007 / 58  (43.5):  23%|██▎       | 58/252 [06:40<21:15,  6.58s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.794s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.547s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.769s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.671s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.608s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.743s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.831s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.210999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 25.650000000000006 / 59  (43.5):  23%|██▎       | 59/252 [06:55<29:55,  9.31s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 26.100000000000005 / 60  (43.5):  24%|██▍       | 60/252 [06:57<22:51,  7.15s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.837s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.924s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 27.000000000000004 / 61  (44.3):  24%|██▍       | 61/252 [07:00<18:12,  5.72s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.397s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.823s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.989s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 27.100000000000005 / 62  (43.7):  25%|██▍       | 62/252 [07:11<23:21,  7.38s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.649s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 27.200000000000006 / 63  (43.2):  25%|██▌       | 63/252 [07:16<20:33,  6.53s/it]INFO:backoff:Backing off request(...) for 7.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.868s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.97s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.674s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.869s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 27.250000000000007 / 64  (42.6):  25%|██▌       | 64/252 [07:23<21:13,  6.77s/it]INFO:backoff:Backing off request(...) for 4.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.757s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 4.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 15.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 15.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.846s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 27.450000000000006 / 65  (42.2):  26%|██▌       | 65/252 [07:34<25:30,  8.18s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.701s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 28.350000000000005 / 66  (43.0):  26%|██▌       | 66/252 [07:37<20:09,  6.50s/it]

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.150000000000006 / 67  (43.5):  27%|██▋       | 67/252 [07:41<18:03,  5.85s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.496s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 4.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.456999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 4.8 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 29.650000000000006 / 68  (43.6):  27%|██▋       | 68/252 [07:49<19:13,  6.27s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 30.150000000000006 / 69  (43.7):  27%|██▋       | 69/252 [07:53<17:39,  5.79s/it]INFO:backoff:Backing off request(...) for 9.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.612s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 9.6 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.873s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.694s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.873s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.938s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 30.650000000000006 / 70  (43.8):  28%|██▊       | 70/252 [08:05<22:37,  7.46s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.484s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.666s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.894s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 31.450000000000006 / 71  (44.3):  28%|██▊       | 71/252 [08:11<21:45,  7.21s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.424s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.493s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.896s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.876s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 31.650000000000006 / 72  (44.0):  29%|██▊       | 72/252 [08:23<25:27,  8.48s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 32.150000000000006 / 73  (44.0):  29%|██▉       | 73/252 [08:25<19:36,  6.57s/it]INFO:backoff:Backing off request(...) for 6.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 6.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.689s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.931s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 32.35000000000001 / 74  (43.7):  29%|██▉       | 74/252 [08:29<17:36,  5.94s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.282s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 32.75000000000001 / 75  (43.7):  30%|██▉       | 75/252 [08:36<18:33,  6.29s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.286s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.728s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.803s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.888s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 33.150000000000006 / 76  (43.6):  30%|███       | 76/252 [08:46<20:56,  7.14s/it]

Backing off 7.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.759s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 33.95 / 77  (44.1):  31%|███       | 77/252 [08:52<20:22,  6.98s/it]INFO:backoff:Backing off request(...) for 2.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.904s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.44s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.849s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 34.300000000000004 / 78  (44.0):  31%|███       | 78/252 [09:03<23:55,  8.25s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.891s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 34.650000000000006 / 79  (43.9):  31%|███▏      | 79/252 [09:06<18:39,  6.47s/it]

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.677s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.921s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 35.10000000000001 / 80  (43.9):  32%|███▏      | 80/252 [09:10<16:51,  5.88s/it]

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.677s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.819s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.776s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 35.50000000000001 / 81  (43.8):  32%|███▏      | 81/252 [09:19<19:16,  6.76s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.847s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.618s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.923s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.694s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.946s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 36.00000000000001 / 82  (43.9):  33%|███▎      | 82/252 [09:30<23:08,  8.17s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.497s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.542s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 36.85000000000001 / 83  (44.4):  33%|███▎      | 83/252 [09:35<19:53,  7.06s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.897s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 37.20000000000001 / 84  (44.3):  33%|███▎      | 84/252 [09:37<15:57,  5.70s/it]

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.769s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 37.60000000000001 / 85  (44.2):  34%|███▎      | 85/252 [09:49<21:00,  7.55s/it]INFO:backoff:Backing off request(...) for 5.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 38.10000000000001 / 86  (44.3):  34%|███▍      | 86/252 [09:51<16:08,  5.84s/it]

Backing off 5.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.648s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 38.650000000000006 / 87  (44.4):  35%|███▍      | 87/252 [09:58<16:48,  6.11s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.569s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.964s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 11.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.483s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.714s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 39.150000000000006 / 88  (44.5):  35%|███▍      | 88/252 [10:08<19:37,  7.18s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.842s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.816s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.622s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 39.550000000000004 / 89  (44.4):  35%|███▌      | 89/252 [10:16<20:52,  7.69s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.795s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.951s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.455s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.958s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.89s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 39.900000000000006 / 90  (44.3):  36%|███▌      | 90/252 [10:23<20:07,  7.46s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.414s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.901s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 40.400000000000006 / 91  (44.4):  36%|███▌      | 91/252 [10:30<19:34,  7.30s/it]INFO:backoff:Backing off request(...) for 6.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.248s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.139s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.2 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.916s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.300000000000004 / 93  (44.4):  37%|███▋      | 93/252 [10:39<14:52,  5.62s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.928s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.898s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.574s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.467s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 5.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.758s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 5.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.978s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.300000000000004 / 94  (43.9):  37%|███▋      | 94/252 [10:53<21:22,  8.12s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.924s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.774s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.476s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.300000000000004 / 95  (43.5):  38%|███▊      | 95/252 [10:58<18:31,  7.08s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.607s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.589s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.68s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 41.75000000000001 / 96  (43.5):  38%|███▊      | 96/252 [11:08<20:59,  8.08s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.899s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.736s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 41.95000000000001 / 97  (43.2):  38%|███▊      | 97/252 [11:11<16:56,  6.56s/it]

Backing off 0.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.806s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.732s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 42.75000000000001 / 98  (43.6):  39%|███▉      | 98/252 [11:18<16:56,  6.60s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.626s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.334s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 42.75000000000001 / 99  (43.2):  39%|███▉      | 99/252 [11:25<16:49,  6.60s/it]INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.738999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.687s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 43.45000000000001 / 100  (43.5):  40%|███▉      | 100/252 [11:31<17:00,  6.72s/it]

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.563s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 43.80000000000001 / 101  (43.4):  40%|████      | 101/252 [11:34<13:32,  5.38s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.803s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.79s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.20000000000001 / 102  (43.3):  40%|████      | 102/252 [11:40<14:19,  5.73s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.28s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.738999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.354s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 44.75000000000001 / 103  (43.4):  41%|████      | 103/252 [11:47<15:04,  6.07s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.841s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.691s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.931s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.764s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.312s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 44.95000000000001 / 104  (43.2):  41%|████▏     | 104/252 [11:57<17:51,  7.24s/it]

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.749s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.869s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.45000000000001 / 105  (43.3):  42%|████▏     | 105/252 [12:06<18:52,  7.71s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.791s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.96s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.708s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.94s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 45.95000000000001 / 106  (43.3):  42%|████▏     | 106/252 [12:13<18:31,  7.61s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.84s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.754s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.00000000000001 / 107  (43.0):  42%|████▏     | 107/252 [12:17<15:36,  6.46s/it]INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.611s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.737s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.634s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.821s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.91s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.934s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.777s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.0 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 46.900000000000006 / 109  (43.0):  43%|████▎     | 109/252 [12:36<17:45,  7.45s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.730999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.811s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.712s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 47.7 / 110  (43.4):  44%|████▎     | 110/252 [12:43<17:21,  7.33s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.585s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.755s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.5 / 111  (43.7):  44%|████▍     | 111/252 [12:47<15:15,  6.49s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.448s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.554s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.071s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 48.9 / 112  (43.7):  44%|████▍     | 112/252 [12:52<13:38,  5.85s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.895s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.66s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.609999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.913s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.359999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.449999999999996 / 113  (43.8):  45%|████▍     | 113/252 [13:06<19:36,  8.46s/it]INFO:backoff:Backing off request(...) for 2.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.708s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 49.949999999999996 / 114  (43.8):  45%|████▌     | 114/252 [13:10<16:27,  7.15s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.625s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.586s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.709s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.4 / 115  (43.8):  46%|████▌     | 115/252 [13:15<14:51,  6.51s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.116s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.281s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.621s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.449999999999996 / 116  (43.5):  46%|████▌     | 116/252 [13:23<15:58,  7.05s/it]INFO:backoff:Backing off request(...) for 8.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.961s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.954s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 50.55 / 117  (43.2):  46%|████▋     | 117/252 [13:31<15:49,  7.03s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.583s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.757s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.942s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.255s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 4.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 50.55 / 118  (42.8):  47%|████▋     | 118/252 [13:40<17:06,  7.66s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.949999999999996 / 119  (42.8):  47%|████▋     | 119/252 [13:42<13:37,  6.15s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.346s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.994s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.661s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 50.99999999999999 / 120  (42.5):  48%|████▊     | 120/252 [13:51<15:23,  6.99s/it]INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.711s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.684s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.684s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 10.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 51.54999999999999 / 121  (42.6):  48%|████▊     | 121/252 [14:03<18:14,  8.35s/it]

Backing off 10.0 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.460999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.844s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 51.74999999999999 / 122  (42.4):  48%|████▊     | 122/252 [14:08<15:53,  7.34s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.76s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 51.79999999999999 / 123  (42.1):  49%|████▉     | 123/252 [14:14<15:20,  7.13s/it]INFO:backoff:Backing off request(...) for 2.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.42s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.899s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 22.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.657s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 22.9 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 52.29999999999999 / 124  (42.2):  49%|████▉     | 124/252 [14:21<15:12,  7.13s/it]INFO:backoff:Backing off request(...) for 4.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.89s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 4.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.989s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.39999999999999 / 126  (42.4):  50%|█████     | 126/252 [14:31<11:47,  5.62s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.644s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.99s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 53.94999999999999 / 127  (42.5):  50%|█████     | 127/252 [14:40<14:08,  6.79s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.814s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.648s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.968s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 54.29999999999999 / 128  (42.4):  51%|█████     | 128/252 [14:51<16:28,  7.97s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.376s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.795s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 54.64999999999999 / 129  (42.4):  51%|█████     | 129/252 [14:56<14:21,  7.00s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 55.54999999999999 / 130  (42.7):  52%|█████▏    | 130/252 [14:58<11:06,  5.46s/it]

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.18s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.738999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.985s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.728s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 56.44999999999999 / 131  (43.1):  52%|█████▏    | 131/252 [15:09<14:28,  7.18s/it]INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.271s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.85s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 57.249999999999986 / 132  (43.4):  52%|█████▏    | 132/252 [15:16<14:06,  7.05s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.298s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 57.649999999999984 / 133  (43.3):  53%|█████▎    | 133/252 [15:20<12:23,  6.25s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.853s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.401s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.941s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.816s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.645s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.681s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 58.649999999999984 / 134  (43.8):  53%|█████▎    | 134/252 [15:30<14:22,  7.31s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 58.749999999999986 / 135  (43.5):  54%|█████▎    | 135/252 [15:32<11:14,  5.76s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.911s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 7.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.925s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.842s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.8s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.649999999999984 / 137  (43.5):  54%|█████▍    | 137/252 [15:46<11:13,  5.86s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.49s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.456999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 59.84999999999999 / 138  (43.4):  55%|█████▍    | 138/252 [15:52<11:33,  6.08s/it]INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.581s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.428s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.460999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.495s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.967s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 60.29999999999998 / 140  (43.1):  56%|█████▌    | 140/252 [16:09<12:21,  6.62s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.813s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.706s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.902s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 61.09999999999998 / 141  (43.3):  56%|█████▌    | 141/252 [16:13<10:57,  5.92s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.769s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.741s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.9s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 61.49999999999998 / 142  (43.3):  56%|█████▋    | 142/252 [16:18<10:16,  5.60s/it]

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.571s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.549999999999976 / 143  (43.0):  57%|█████▋    | 143/252 [16:25<10:50,  5.96s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.389s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.351999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.797s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.626s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.601999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.415s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.99s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.911s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 61.74999999999998 / 144  (42.9):  57%|█████▋    | 144/252 [16:40<15:48,  8.79s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.815s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.437s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.551s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 62.09999999999998 / 145  (42.8):  58%|█████▊    | 145/252 [16:44<13:21,  7.49s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.808s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.775s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.922s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 62.04999999999998 / 146  (42.5):  58%|█████▊    | 146/252 [16:49<11:38,  6.59s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.515s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.471s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 62.59999999999998 / 147  (42.6):  58%|█████▊    | 147/252 [16:56<11:38,  6.65s/it]INFO:backoff:Backing off request(...) for 3.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.444s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.782s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.709s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.79s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 6.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.677s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 6.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 63.09999999999998 / 148  (42.6):  59%|█████▊    | 148/252 [17:05<13:01,  7.52s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.903s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 13.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 13.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.955s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 63.59999999999998 / 149  (42.7):  59%|█████▉    | 149/252 [17:17<14:53,  8.68s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.909s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 63.94999999999998 / 150  (42.6):  60%|█████▉    | 150/252 [17:19<11:27,  6.74s/it]

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.42s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.577s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.893s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 64.14999999999998 / 151  (42.5):  60%|█████▉    | 151/252 [17:30<13:40,  8.13s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 5.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.781s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 5.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 64.59999999999998 / 152  (42.5):  60%|██████    | 152/252 [17:33<10:50,  6.50s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.554s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.39999999999998 / 153  (42.7):  61%|██████    | 153/252 [17:37<09:36,  5.82s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.755s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 65.59999999999998 / 154  (42.6):  61%|██████    | 154/252 [17:41<08:47,  5.38s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.788s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.406s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.705s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.889s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 65.79999999999998 / 155  (42.5):  62%|██████▏   | 155/252 [17:46<08:17,  5.13s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.62s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.863999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.78s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.458s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.39999999999998 / 156  (42.6):  62%|██████▏   | 156/252 [17:57<11:15,  7.04s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.676s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.792s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.605999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.957s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 66.79999999999998 / 157  (42.5):  62%|██████▏   | 157/252 [18:07<12:09,  7.68s/it]

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.755s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.572s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 66.89999999999998 / 158  (42.3):  63%|██████▎   | 158/252 [18:13<11:32,  7.37s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.829s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.617s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.963s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.49999999999997 / 159  (42.5):  63%|██████▎   | 159/252 [18:23<12:19,  7.95s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.659s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.824s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.879s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 67.84999999999997 / 160  (42.4):  63%|██████▎   | 160/252 [18:28<10:55,  7.13s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.821s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 68.24999999999997 / 161  (42.4):  64%|██████▍   | 161/252 [18:32<09:27,  6.23s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.635s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.846s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.612s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.88s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 69.09999999999997 / 162  (42.7):  64%|██████▍   | 162/252 [18:39<09:35,  6.40s/it]

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.904s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 69.04999999999997 / 163  (42.4):  65%|██████▍   | 163/252 [18:41<07:38,  5.15s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.806s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.987s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.93s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.368s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.44999999999997 / 164  (42.3):  65%|██████▌   | 164/252 [18:50<09:13,  6.29s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.444s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.609999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.917s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.678s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 69.79999999999997 / 165  (42.3):  65%|██████▌   | 165/252 [18:57<09:15,  6.39s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.551s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.518s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.995s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 6.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.564s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.929s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 70.29999999999997 / 166  (42.3):  66%|██████▌   | 166/252 [19:06<10:23,  7.25s/it]

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.968s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.954s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.68s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.39999999999996 / 167  (42.2):  66%|██████▋   | 167/252 [19:17<12:03,  8.51s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.634s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.897s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 70.49999999999996 / 168  (42.0):  67%|██████▋   | 168/252 [19:20<09:18,  6.65s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.936s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.499s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.24999999999996 / 169  (42.2):  67%|██████▋   | 169/252 [19:24<08:14,  5.95s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.866s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 6.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.841s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 6.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.583s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.74s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.562s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 71.29999999999995 / 170  (41.9):  67%|██████▋   | 170/252 [19:37<11:16,  8.25s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.959s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 71.79999999999995 / 171  (42.0):  68%|██████▊   | 171/252 [19:40<08:47,  6.51s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.432s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.675s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.497s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.333s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 72.59999999999995 / 172  (42.2):  68%|██████▊   | 172/252 [19:47<08:42,  6.53s/it]INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.771s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.544s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.962s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.663s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.478s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.09999999999995 / 173  (42.3):  69%|██████▊   | 173/252 [19:55<09:32,  7.25s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.886s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.423s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 73.59999999999995 / 174  (42.3):  69%|██████▉   | 174/252 [20:02<09:17,  7.15s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.475s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.932s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 74.09999999999995 / 175  (42.3):  69%|██████▉   | 175/252 [20:09<08:56,  6.97s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.813s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 74.19999999999995 / 176  (42.2):  70%|██████▉   | 176/252 [20:11<07:04,  5.58s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.190999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.902s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 74.69999999999995 / 177  (42.2):  70%|███████   | 177/252 [20:16<06:28,  5.18s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.46s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.549s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 75.59999999999995 / 178  (42.5):  71%|███████   | 178/252 [20:22<06:57,  5.64s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.683s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.4 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 14.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.587s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.593999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 14.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.693s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.879s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 75.69999999999995 / 179  (42.3):  71%|███████   | 179/252 [20:31<08:10,  6.71s/it]

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.982s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.49999999999994 / 180  (42.5):  71%|███████▏  | 180/252 [20:39<08:15,  6.88s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.491s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 76.99999999999994 / 181  (42.5):  72%|███████▏  | 181/252 [20:46<08:11,  6.92s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 25.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.616s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 25.8 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.854s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.709s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 77.54999999999994 / 183  (42.4):  73%|███████▎  | 183/252 [20:57<06:58,  6.07s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.413s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 78.54999999999994 / 184  (42.7):  73%|███████▎  | 184/252 [21:07<07:57,  7.03s/it]INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.803s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.828s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.04999999999994 / 185  (42.7):  73%|███████▎  | 185/252 [21:14<07:50,  7.02s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.547s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 33.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.478s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 33.7 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.902s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 79.49999999999994 / 186  (42.7):  74%|███████▍  | 186/252 [21:19<07:08,  6.50s/it]INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.452999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.919s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.579s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 80.39999999999995 / 187  (43.0):  74%|███████▍  | 187/252 [21:26<07:07,  6.57s/it]INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.952s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 81.34999999999995 / 189  (43.0):  75%|███████▌  | 189/252 [21:38<06:24,  6.11s/it]INFO:backoff:Backing off request(...) for 9.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.609s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 9.6 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 81.44999999999995 / 190  (42.9):  75%|███████▌  | 190/252 [21:48<07:21,  7.11s/it]

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.853s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 21.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.726999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 21.6 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.718999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 81.54999999999994 / 191  (42.7):  76%|███████▌  | 191/252 [21:57<07:47,  7.66s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.868s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.04999999999994 / 192  (42.7):  76%|███████▌  | 192/252 [22:04<07:23,  7.40s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.992s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.49999999999994 / 193  (42.7):  77%|███████▋  | 193/252 [22:11<07:07,  7.24s/it]INFO:backoff:Backing off request(...) for 3.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.708s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.2 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.799s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.675s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.6 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.673s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.805s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.327s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.59999999999994 / 194  (42.6):  77%|███████▋  | 194/252 [22:24<08:45,  9.06s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.5s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 82.94999999999993 / 195  (42.5):  77%|███████▋  | 195/252 [22:26<06:40,  7.03s/it]INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.54s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.736s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.873s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 83.14999999999993 / 196  (42.4):  78%|███████▊  | 196/252 [22:31<05:51,  6.27s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.887s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.699s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.748s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.54999999999994 / 197  (42.4):  78%|███████▊  | 197/252 [22:37<05:51,  6.39s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.589s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 83.94999999999995 / 198  (42.4):  79%|███████▊  | 198/252 [22:40<04:40,  5.19s/it]INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 3.344999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.77s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.8s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.892s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 84.34999999999995 / 199  (42.4):  79%|███████▉  | 199/252 [22:51<06:15,  7.08s/it]INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.728s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.631s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.976s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.440999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 84.44999999999995 / 200  (42.2):  79%|███████▉  | 200/252 [22:58<06:05,  7.04s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.505s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.838s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.901s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 84.74999999999994 / 202  (42.0):  80%|████████  | 202/252 [23:07<04:35,  5.51s/it]INFO:backoff:Backing off request(...) for 6.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.502s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 6.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.279s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.976s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.95s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 85.54999999999994 / 203  (42.1):  81%|████████  | 203/252 [23:16<05:28,  6.71s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.775s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.34999999999994 / 204  (42.3):  81%|████████  | 204/252 [23:21<04:48,  6.01s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.846s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.633s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.468999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.975s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.419s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.757s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.34999999999994 / 205  (42.1):  81%|████████▏ | 205/252 [23:28<05:03,  6.45s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.377s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 11.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.924s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.758s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 11.1 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.909s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 86.84999999999994 / 206  (42.2):  82%|████████▏ | 206/252 [23:39<05:52,  7.66s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.784s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.565s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.358s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.661s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.825s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 87.44999999999995 / 208  (42.0):  83%|████████▎ | 208/252 [23:50<04:34,  6.24s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.837s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.656s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.486s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.796s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.24999999999994 / 209  (42.2):  83%|████████▎ | 209/252 [23:56<04:32,  6.33s/it]INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.896s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.456s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.885s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 88.49999999999994 / 210  (42.1):  83%|████████▎ | 210/252 [24:03<04:31,  6.45s/it]INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.712s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.741s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.751s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 88.99999999999994 / 211  (42.2):  84%|████████▎ | 211/252 [24:10<04:25,  6.47s/it]INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.475s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.744s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.966s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 89.39999999999995 / 212  (42.2):  84%|████████▍ | 212/252 [24:16<04:22,  6.56s/it]INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.866s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.526s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.0 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.38s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.986s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 89.59999999999995 / 213  (42.1):  85%|████████▍ | 213/252 [24:21<03:51,  5.94s/it]

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.73s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.588s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.734999999s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.455s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.875s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 2.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.87s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 2.3 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 90.49999999999996 / 214  (42.3):  85%|████████▍ | 214/252 [24:32<04:47,  7.57s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.75s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 90.99999999999996 / 215  (42.3):  85%|████████▌ | 215/252 [24:34<03:40,  5.97s/it]INFO:backoff:Backing off request(...) for 7.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.716s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.519s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 7.3 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.767s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 3.0 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.968s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.49999999999996 / 216  (42.4):  86%|████████▌ | 216/252 [24:48<04:57,  8.26s/it]INFO:backoff:Backing off request(...) for 8.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.437s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 8.5 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 91.59999999999995 / 217  (42.2):  86%|████████▌ | 217/252 [24:51<03:48,  6.54s/it]INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.218s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.1 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.746s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.989s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.583s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 91.64999999999995 / 218  (42.0):  87%|████████▋ | 218/252 [25:00<04:09,  7.34s/it]

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.587s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 92.19999999999995 / 219  (42.1):  87%|████████▋ | 219/252 [25:06<03:52,  7.04s/it]INFO:backoff:Backing off request(...) for 1.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.288s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.654s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.57s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.4 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 92.74999999999994 / 220  (42.2):  87%|████████▋ | 220/252 [25:13<03:44,  7.00s/it]INFO:backoff:Backing off request(...) for 1.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.757s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.611s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.2 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.83s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.777s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.835s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.715s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.962s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 93.74999999999994 / 221  (42.4):  88%|████████▊ | 221/252 [25:23<04:00,  7.75s/it]

Backing off 0.5 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.628s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.9 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.684s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.911s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 93.84999999999994 / 222  (42.3):  88%|████████▊ | 222/252 [25:29<03:44,  7.48s/it]

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.732s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.819s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 94.44999999999993 / 223  (42.4):  88%|████████▊ | 223/252 [25:34<03:12,  6.63s/it]INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.698s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 94.49999999999993 / 224  (42.2):  89%|████████▉ | 224/252 [25:36<02:29,  5.32s/it]

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.872s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.766s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 95.09999999999992 / 225  (42.3):  89%|████████▉ | 225/252 [25:41<02:16,  5.04s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.884s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.664s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.944s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.807s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.9 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.9 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.72s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.615s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.673s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.649s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.3 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 95.99999999999993 / 226  (42.5):  90%|████████▉ | 226/252 [25:56<03:33,  8.21s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.704s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.544s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.1 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.1s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.983s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.1 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 96.79999999999993 / 227  (42.6):  90%|█████████ | 227/252 [26:03<03:15,  7.83s/it]INFO:backoff:Backing off request(...) for 3.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.511s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.6 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.856s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.948s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.7 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 4.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.612s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 96.89999999999992 / 228  (42.5):  90%|█████████ | 228/252 [26:11<03:03,  7.66s/it]

Backing off 4.4 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 96.99999999999991 / 229  (42.4):  91%|█████████ | 229/252 [26:14<02:25,  6.31s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 1.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.773s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 1.5 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.09999999999991 / 230  (42.2):  91%|█████████▏| 230/252 [26:19<02:15,  6.16s/it]INFO:backoff:Backing off request(...) for 0.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.426s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.357s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.8 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.2s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.627s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.2 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 2.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.851s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.791s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.6 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 97.29999999999991 / 231  (42.1):  92%|█████████▏| 231/252 [26:29<02:30,  7.16s/it]

Backing off 1.0 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 9.0s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.888s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 9.0 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.52s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.49999999999991 / 232  (42.0):  92%|█████████▏| 232/252 [26:36<02:22,  7.10s/it]INFO:backoff:Backing off request(...) for 0.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.641s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.8 seconds after 4 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 3.8s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.988s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 3.8 seconds after 5 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 97.94999999999992 / 233  (42.0):  92%|█████████▏| 233/252 [26:43<02:13,  7.05s/it]INFO:backoff:Backing off request(...) for 19.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.266s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 19.4 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 27.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.801s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 98.29999999999991 / 234  (42.0):  93%|█████████▎| 234/252 [26:50<02:06,  7.02s/it]

Backing off 27.3 seconds after 6 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.871s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 99.04999999999991 / 236  (42.0):  94%|█████████▎| 236/252 [27:01<01:37,  6.08s/it]INFO:backoff:Backing off request(...) for 39.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.814s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 39.3 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.859s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 100.29999999999991 / 238  (42.1):  94%|█████████▍| 238/252 [27:18<01:37,  6.96s/it]INFO:backoff:Backing off request(...) for 33.9s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.755s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
INFO:backoff:Backing off request(...) for 0.3s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.619s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 33.9 seconds after 7 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}
Backing off 0.3 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.04999999999991 / 242  (42.2):  96%|█████████▌| 242/252 [27:44<01:01,  6.15s/it]INFO:backoff:Backing off request(...) for 107.6s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.634s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 107.6 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.1499999999999 / 243  (42.0):  96%|█████████▋| 243/252 [27:55<01:09,  7.75s/it]INFO:backoff:Backing off request(...) for 109.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.809s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})
Average Metric: 102.54999999999991 / 244  (42.0):  97%|█████████▋| 244/252 [27:58<00:49,  6.17s/it]

Backing off 109.7 seconds after 8 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.94999999999992 / 245  (42.0):  97%|█████████▋| 245/252 [28:07<00:49,  7.06s/it]INFO:backoff:Backing off request(...) for 0.5s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.82s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.5 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

INFO:backoff:Backing off request(...) for 1.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.927s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 1.7 seconds after 2 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 102.99999999999991 / 246  (41.9):  98%|█████████▊| 246/252 [28:14<00:43,  7.17s/it]INFO:backoff:Backing off request(...) for 2.7s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.882s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 2.7 seconds after 3 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 103.54999999999991 / 248  (41.8):  98%|█████████▊| 248/252 [28:28<00:28,  7.05s/it]INFO:backoff:Backing off request(...) for 0.4s (groq.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j1skxws6et3tfhe3vj2hffj6` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.912s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'requests', 'code': 'rate_limit_exceeded'}})

Backing off 0.4 seconds after 1 tries calling function <function GroqLM.request at 0x7a83ec50ba30> with kwargs {}

Average Metric: 105.6999999999999 / 252  (41.9): 100%|██████████| 252/252 [29:49<00:00,  7.10s/it]

In [ ]:
compiled_rag.save('/content/drive/MyDrive/chroma/final_optimizer.json')

In [ ]:
compiled_rag=RAG()
compiled_rag.load(path='/content/drive/MyDrive/chroma/final_optimizer.json')

In [ ]:
#evaluate
from dspy.evaluate.evaluate import Evaluate
# Set up the `evaluate_on_qa` function. We'll use this many times below.
evaluate_on_qa = Evaluate(devset=test_df, num_threads=1, display_progress=True, display_table=5)


evaluate_on_qa(compiled_rag, metric=metric)

Average Metric: 27.24999999999999 / 63  (43.3): 100%|██████████| 63/63 [07:03<00:00,  6.71s/it]

43.25

### Chatbot

In [ ]:
client = Groq(
    api_key= os.environ['GROQ_API_KEY'],
)
def llama3(query):
  chat_completion = client.chat.completions.create(
      messages=[
          {
              "role": "user",
              "content": query,
          }
      ],
      model="llama3-70b-8192",
  )
  return chat_completion.choices[0].message.content
# print(response('hi'))

In [ ]:
import gradio as gr
import time

def chatbot_interface(user_input, chat_history=[]):
    response = compiled_rag(user_input)

    # if (60 < len(response.answer) < 250) and ('reason' not in response.answer):
    if (60 < len(response.answer) < 250) and ('reason' or 'question seems to be missing') not in response.answer.lower():
        bot_response = "RAG: " + response.answer
    else:
        bot_response = "L3: " + llama3(f"Answer concisely and politely by considering all the information from {response} to respond to the question: {user_input}. Make use of {chat_history[:300]} if it exists.")

    chat_history.append((user_input, bot_response))
    return "", chat_history

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox(placeholder="Type your message here...")
    clear = gr.ClearButton([msg, chatbot])

    msg.submit(chatbot_interface, [msg, chatbot], [msg, chatbot])

demo.launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://0d429beeca23d5f144.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)